// Dynamic definition of 100 university-level Economics textbooks for MBSTU Economics Library

export interface DefaultEconBook {
  title: string;
  author: string;
  category: string;
  cover: string;
  bookId: string;
  shelfNo: string;
  status: 'available' | 'pre-order';
  price: string;
  stock: number;
  isEBook: boolean;
  ebookUrl?: string;
}

// 10 sections of Economics:
// 1. Microeconomics
// 2. Macroeconomics
// 3. Econometrics & Statistics
// 4. International Economics
// 5. Development Economics
// 6. Bangladesh Economy
// 7. Mathematical Economics
// 8. Public Finance
// 9. Environmental Economics
// 10. Financial Economics & Banking

export const defaultEconBooks: DefaultEconBook[] = [
  // ==================== 1. MICROECONOMICS (10 Books) ====================
  {
    title: "Microeconomic Theory: Basic Principles and Extensions",
    author: "Walter Nicholson & Christopher Snyder",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1001",
    shelfNo: "M-1",
    status: "available",
    price: "৳৪৮০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Intermediate Microeconomics: A Modern Approach",
    author: "Hal R. Varian",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1002",
    shelfNo: "M-1",
    status: "available",
    price: "৳৪৫০",
    stock: 6,
    isEBook: false
  },
  {
    title: "Principles of Microeconomics",
    author: "N. Gregory Mankiw",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1003",
    shelfNo: "M-2",
    status: "available",
    price: "৳৩৫০",
    stock: 8,
    isEBook: false
  },
  {
    title: "Microeconomics",
    author: "Robert S. Pindyck & Daniel L. Rubinfeld",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1004",
    shelfNo: "M-2",
    status: "available",
    price: "৳৫২০",
    stock: 4,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-pindyck/view"
  },
  {
    title: "ব্যষ্টিগত অর্থনীতি বিশ্লেষণ (Microeconomic Analysis Bengali)",
    author: "ড. মোস্তাফিজুর রহমান",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1005",
    shelfNo: "M-3",
    status: "available",
    price: "৳২৮০",
    stock: 7,
    isEBook: false
  },
  {
    title: "Microeconomic Analysis",
    author: "Hal R. Varian",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1006",
    shelfNo: "M-1",
    status: "available",
    price: "৳৫৫০",
    stock: 3,
    isEBook: false
  },
  {
    title: "Advanced Microeconomic Theory",
    author: "Geoffrey A. Jehle & Philip J. Reny",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1007",
    shelfNo: "M-3",
    status: "available",
    price: "৳৬৫০",
    stock: 2,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-jehle/view"
  },
  {
    title: "Microeconomics: Theory and Applications",
    author: "Dominick Salvatore",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1008",
    shelfNo: "M-2",
    status: "available",
    price: "৳৩৯০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Game Theory for Applied Economists",
    author: "Robert Gibbons",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1009",
    shelfNo: "M-4",
    status: "available",
    price: "৳৩৩০",
    stock: 4,
    isEBook: false
  },
  {
    title: "ব্যষ্টিগত অর্থনীতি পরিচিতি (Introduction to Microeconomics Bengali)",
    author: "এম. এ. জলিল",
    category: "Microeconomics (ব্যষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400",
    bookId: "MIC-1010",
    shelfNo: "M-4",
    status: "available",
    price: "৳২০০",
    stock: 10,
    isEBook: false
  },

  // ==================== 2. MACROECONOMICS (10 Books) ====================
  {
    title: "Macroeconomics",
    author: "N. Gregory Mankiw",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&sig=1",
    bookId: "MAC-2001",
    shelfNo: "MC-1",
    status: "available",
    price: "৳৪৮০",
    stock: 6,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-mankiw-macro/view"
  },
  {
    title: "Macroeconomics: Policy and Practice",
    author: "Frederic S. Mishkin",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&sig=2",
    bookId: "MAC-2002",
    shelfNo: "MC-1",
    status: "available",
    price: "৳৪২০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Macroeconomics",
    author: "Olivier Blanchard",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&sig=3",
    bookId: "MAC-2003",
    shelfNo: "MC-2",
    status: "available",
    price: "৳৪৯০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Advanced Macroeconomics",
    author: "David Romer",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400&sig=4",
    bookId: "MAC-2004",
    shelfNo: "MC-3",
    status: "available",
    price: "৳৫৮০",
    stock: 3,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-romer-macro/view"
  },
  {
    title: "সমষ্টিগত অর্থনীতি পাঠ (Macroeconomics Readings Study)",
    author: "অধ্যাপক খন্দকার রাইহান",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400&sig=5",
    bookId: "MAC-2005",
    shelfNo: "MC-4",
    status: "available",
    price: "৳২৫০",
    stock: 6,
    isEBook: false
  },
  {
    title: "Macroeconomic Theory",
    author: "M. L. Jhingan",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&sig=6",
    bookId: "MAC-2006",
    shelfNo: "MC-2",
    status: "available",
    price: "৳৩৫০",
    stock: 9,
    isEBook: false
  },
  {
    title: "Principles of Macroeconomics",
    author: "Karl E. Case, Ray C. Fair & Sharon M. Oster",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&sig=7",
    bookId: "MAC-2007",
    shelfNo: "MC-3",
    status: "available",
    price: "৳৪০০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Macroeconomics: Theories and Policies",
    author: "Richard T. Froyen",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&sig=8",
    bookId: "MAC-2008",
    shelfNo: "MC-2",
    status: "available",
    price: "৳৪৩০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Foundations of Modern Macroeconomics",
    author: "Ben J. Heijdra",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400&sig=9",
    bookId: "MAC-2009",
    shelfNo: "MC-5",
    status: "available",
    price: "৳৬০০",
    stock: 2,
    isEBook: false
  },
  {
    title: "সমষ্টিগত অর্থবিদ্যার মূলকথা (Essentials of Macroeconomics)",
    author: " ড. মো: জামাল উদ্দীন",
    category: "Macroeconomics (সমষ্টিগত অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400&sig=10",
    bookId: "MAC-2010",
    shelfNo: "MC-4",
    status: "available",
    price: "৳২৬০",
    stock: 8,
    isEBook: false
  },

  // ==================== 3. ECONOMETRICS & STATISTICS (10 Books) ====================
  {
    title: "Basic Econometrics",
    author: "Damodar N. Gujarati & Dawn C. Porter",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&sig=11",
    bookId: "ECO-3001",
    shelfNo: "EC-1",
    status: "available",
    price: "৳৫২০",
    stock: 5,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-gujarati/view"
  },
  {
    title: "Introductory Econometrics: A Modern Approach",
    author: "Jeffrey M. Wooldridge",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&sig=12",
    bookId: "ECO-3002",
    shelfNo: "EC-1",
    status: "available",
    price: "৳৬১০",
    stock: 4,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-wooldridge/view"
  },
  {
    title: "Econometric Analysis",
    author: "William H. Greene",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&sig=13",
    bookId: "ECO-3003",
    shelfNo: "EC-2",
    status: "available",
    price: "৳৭৫০",
    stock: 2,
    isEBook: false
  },
  {
    title: "Introduction to Econometrics",
    author: "James H. Stock & Mark W. Watson",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400&sig=14",
    bookId: "ECO-3004",
    shelfNo: "EC-2",
    status: "available",
    price: "৳৫৪০",
    stock: 3,
    isEBook: false
  },
  {
    title: "ইকোনোমেট্রিক্স পরিচিতি (Introduction to Econometrics Bengali)",
    author: "ড. মুহম্মদ মাহবুব আলী",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400&sig=15",
    bookId: "ECO-3005",
    shelfNo: "EC-3",
    status: "available",
    price: "৳৩০০",
    stock: 6,
    isEBook: false
  },
  {
    title: "Using Econometrics: A Practical Guide",
    author: "A. H. Studenmund",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&sig=16",
    bookId: "ECO-3006",
    shelfNo: "EC-3",
    status: "available",
    price: "৳৪৮০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Microeconometrics: Methods and Applications",
    author: "A. Colin Cameron & Pravin K. Trivedi",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&sig=17",
    bookId: "ECO-3007",
    shelfNo: "EC-4",
    status: "available",
    price: "৳৮০০",
    stock: 2,
    isEBook: false
  },
  {
    title: "Econometrics by Example",
    author: "Damodar Gujarati",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&sig=18",
    bookId: "ECO-3008",
    shelfNo: "EC-2",
    status: "available",
    price: "৳৪৫০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Applied Econometric Time Series",
    author: "Walter Enders",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400&sig=19",
    bookId: "ECO-3009",
    shelfNo: "EC-4",
    status: "available",
    price: "৳৫৬০",
    stock: 3,
    isEBook: false
  },
  {
    title: "ব্যবহারিক পরিসংখ্যান ও ইকোনোমেট্রিক্স (Statistics and Econometrics)",
    author: "মো: আব্দুল আউয়াল মিঞা",
    category: "Econometrics (ইকোনোমেট্রিক্স)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400&sig=20",
    bookId: "ECO-3010",
    shelfNo: "EC-3",
    status: "available",
    price: "৳৩২০",
    stock: 5,
    isEBook: false
  },

  // ==================== 4. DEVELOPMENT ECONOMICS (10 Books) ====================
  {
    title: "Economic Development",
    author: "Michael P. Todaro & Stephen C. Smith",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&sig=21",
    bookId: "DEV-4001",
    shelfNo: "D-1",
    status: "available",
    price: "৳৫৩০",
    stock: 7,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-todaro/view"
  },
  {
    title: "Development Economics",
    author: "Debraj Ray",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&sig=22",
    bookId: "DEV-4002",
    shelfNo: "D-1",
    status: "available",
    price: "৳৪৯০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Poor Economics: A Radical Rethinking of the Way to Fight Global Poverty",
    author: "Abhijit V. Banerjee & Esther Duflo",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&sig=23",
    bookId: "DEV-4003",
    shelfNo: "D-2",
    status: "available",
    price: "৳৩২০",
    stock: 12,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-poorecon/view"
  },
  {
    title: "Why Nations Fail: The Origins of Power, Prosperity, and Poverty",
    author: "Daron Acemoglu & James A. Robinson",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400&sig=24",
    bookId: "DEV-4004",
    shelfNo: "D-2",
    status: "available",
    price: "৳৩৫০",
    stock: 10,
    isEBook: false
  },
  {
    title: "উন্নয়ন অর্থনীতি: তত্ত্ব ও বিশ্লেষণ (Development Economics Bengali)",
    author: "ড. আবুল বারকাত",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400&sig=25",
    bookId: "DEV-4005",
    shelfNo: "D-3",
    status: "available",
    price: "৳৩৪০",
    stock: 6,
    isEBook: false
  },
  {
    title: "Development as Freedom",
    author: "Amartya Sen",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&sig=26",
    bookId: "DEV-4006",
    shelfNo: "D-3",
    status: "available",
    price: "৳২৫০",
    stock: 8,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-amartyasen/view"
  },
  {
    title: "The Elusive Quest for Growth",
    author: "William Easterly",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&sig=27",
    bookId: "DEV-4007",
    shelfNo: "D-4",
    status: "available",
    price: "৳৪৫০",
    stock: 4,
    isEBook: false
  },
  {
    title: "An Introduction to Development Economics",
    author: "Pranab Bardhan",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&sig=28",
    bookId: "DEV-4008",
    shelfNo: "D-2",
    status: "available",
    price: "৳২৯০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Economics of Development",
    author: "Dwight H. Perkins, Steven Radelet & David L. Lindauer",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400&sig=29",
    bookId: "DEV-4009",
    shelfNo: "D-4",
    status: "available",
    price: "৳৫৭০",
    stock: 3,
    isEBook: false
  },
  {
    title: "দারিদ্র্য ও উন্নয়ন বিতর্ক (Poverty and Development Debate)",
    author: "অধ্যাপক ড. সেলিম জাহান",
    category: "Development Economics (উন্নয়ন অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400&sig=30",
    bookId: "DEV-4010",
    shelfNo: "D-3",
    status: "available",
    price: "৳২৭০",
    stock: 7,
    isEBook: false
  },

  // ==================== 5. INTERNATIONAL ECONOMICS (10 Books) ====================
  {
    title: "International Economics: Theory and Policy",
    author: "Paul R. Krugman, Maurice Obstfeld & Marc Melitz",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&sig=31",
    bookId: "INT-5001",
    shelfNo: "I-1",
    status: "available",
    price: "৳৫৫০",
    stock: 6,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-krugman/view"
  },
  {
    title: "International Economics",
    author: "Dominick Salvatore",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&sig=32",
    bookId: "INT-5002",
    shelfNo: "I-1",
    status: "available",
    price: "৳৫১০",
    stock: 5,
    isEBook: false
  },
  {
    title: "International Trade",
    author: "Robert C. Feenstra & Alan M. Taylor",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&sig=33",
    bookId: "INT-5003",
    shelfNo: "I-2",
    status: "available",
    price: "৳৪৯০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Globalization and Its Discontents",
    author: "Joseph E. Stiglitz",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400&sig=34",
    bookId: "INT-5004",
    shelfNo: "I-2",
    status: "available",
    price: "৳২৭০",
    stock: 9,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-stiglitz/view"
  },
  {
    title: "আন্তর্জাতিক অর্থনীতি নীতি (International Economics Bengali)",
    author: " ড. এম. এ. তসলিম",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400&sig=35",
    bookId: "INT-5005",
    shelfNo: "I-3",
    status: "available",
    price: "৳৩১০",
    stock: 5,
    isEBook: false
  },
  {
    title: "International Macroeconomics",
    author: "Stephanie Schmitt-Grohé & Martin Uribe",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&sig=36",
    bookId: "INT-5006",
    shelfNo: "I-3",
    status: "available",
    price: "৳৫২০",
    stock: 3,
    isEBook: false
  },
  {
    title: "Advanced International Trade: Theory and Evidence",
    author: "Robert C. Feenstra",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&sig=37",
    bookId: "INT-5007",
    shelfNo: "I-4",
    status: "available",
    price: "৳৬৪০",
    stock: 2,
    isEBook: false
  },
  {
    title: "International Economics: An Introduction",
    author: "Bo Sodersten & Geoffrey Reed",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&sig=38",
    bookId: "INT-5008",
    shelfNo: "I-2",
    status: "available",
    price: "৳৩৯০",
    stock: 4,
    isEBook: false
  },
  {
    title: "The Travels of a T-Shirt in the Global Economy",
    author: "Pietra Rivoli",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400&sig=39",
    bookId: "INT-5009",
    shelfNo: "I-4",
    status: "available",
    price: "৳৩৪০",
    stock: 6,
    isEBook: false
  },
  {
    title: "রপ্তানি বাণিজ্য ও বিশ্বায়ন (Export Trade and Globalization)",
    author: "ড. মোজাফফর আহমেদ",
    category: "International Economics (আন্তর্জাতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400&sig=40",
    bookId: "INT-5010",
    shelfNo: "I-3",
    status: "available",
    price: "৳২৩০",
    stock: 8,
    isEBook: false
  },

  // ==================== 6. BANGLADESH ECONOMY (10 Books) ====================
  {
    title: "The Economy of Bangladesh: Problems and Prospects",
    author: "Azizur Rahman Khan",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&sig=41",
    bookId: "BD-6001",
    shelfNo: "BD-1",
    status: "available",
    price: "৳৩৫০",
    stock: 8,
    isEBook: false
  },
  {
    title: "Bangladesh Economy in the 21st Century",
    author: "Wahiduddin Mahmud",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&sig=42",
    bookId: "BD-6002",
    shelfNo: "BD-1",
    status: "available",
    price: "৳৪০০",
    stock: 5,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-wahiduddin/view"
  },
  {
    title: "Macroeconomic Management in Bangladesh Integration and Reforms",
    author: "Mustafizur Rahman",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&sig=43",
    bookId: "BD-6003",
    shelfNo: "BD-2",
    status: "available",
    price: "৳৪৫০",
    stock: 4,
    isEBook: false
  },
  {
    title: "বাংলাদেশ অর্থনীতি ও কৃষির রূপান্তর (Bangladesh Economy & Agri Bengali)",
    author: "ড. খোন্দকার ইব্রাহিম খালেদ",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400&sig=44",
    bookId: "BD-6004",
    shelfNo: "BD-2",
    status: "available",
    price: "৳২৮০",
    stock: 6,
    isEBook: false
  },
  {
    title: "বাংলাদেশ অর্থনীতি: সমসাময়িক বিতর্ক (Bangladesh Economy: Contemporary Debates)",
    author: "ড. দেবপ্রিয় ভট্টাচার্য",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400&sig=45",
    bookId: "BD-6005",
    shelfNo: "BD-3",
    status: "available",
    price: "৳৩২০",
    stock: 8,
    isEBook: false
  },
  {
    title: "Microfinance and Poverty in Bangladesh",
    author: "Shahidur R. Khandker",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&sig=46",
    bookId: "BD-6006",
    shelfNo: "BD-3",
    status: "available",
    price: "৳৩৫০",
    stock: 5,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-microfinance/view"
  },
  {
    title: "Fifty Years of Bangladesh: Economy, Politics and Society",
    author: "Rehman Sobhan",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&sig=47",
    bookId: "BD-6007",
    shelfNo: "BD-1",
    status: "available",
    price: "৳৫০০",
    stock: 6,
    isEBook: false
  },
  {
    title: "Macroeconomic Policy in Bangladesh",
    author: "Mirza Azizul Islam",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&sig=48",
    bookId: "BD-6008",
    shelfNo: "BD-4",
    status: "available",
    price: "৳৪৫০",
    stock: 3,
    isEBook: false
  },
  {
    title: "বাংলাদেশের অর্থনৈতিক ইতিহাস (Economic History of Bangladesh)",
    author: "আবুল কালাম শামসুদ্দীন",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400&sig=49",
    bookId: "BD-6009",
    shelfNo: "BD-3",
    status: "available",
    price: "৳২৪০",
    stock: 7,
    isEBook: false
  },
  {
    title: "বাংলাদেশের বাজেট ও সামষ্টিক অর্থনৈতিক গতিধারা (BD Budget & Macro)",
    author: "ড. সেলিম রায়হান",
    category: "Bangladesh Economy (বাংলাদেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400&sig=50",
    bookId: "BD-6010",
    shelfNo: "BD-4",
    status: "available",
    price: "৳৩০০",
    stock: 9,
    isEBook: false
  },

  // ==================== 7. MATHEMATICAL ECONOMICS (10 Books) ====================
  {
    title: "Fundamental Methods of Mathematical Economics",
    author: "Alpha C. Chiang & Kevin Wainwright",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&sig=51",
    bookId: "MAT-7001",
    shelfNo: "MA-1",
    status: "available",
    price: "৳৫৫০",
    stock: 6,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-chiang/view"
  },
  {
    title: "Mathematics for Economists",
    author: "Carl P. Simon & Lawrence Blume",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&sig=52",
    bookId: "MAT-7002",
    shelfNo: "MA-1",
    status: "available",
    price: "৳৬৫০",
    stock: 3,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-simonblume/view"
  },
  {
    title: "Mathematics for Economic Analysis",
    author: "Knut Sydsæter & Peter J. Hammond",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&sig=53",
    bookId: "MAT-7003",
    shelfNo: "MA-2",
    status: "available",
    price: "৳৫২০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Introduction to Mathematical Economics",
    author: "Edward T. Dowling (Schaum's Outlines)",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400&sig=54",
    bookId: "MAT-7004",
    shelfNo: "MA-2",
    status: "available",
    price: "৳৩৩০",
    stock: 8,
    isEBook: false
  },
  {
    title: "গাণিতিক অর্থনীতি পরিচিতি (Introduction to Mathematical Economics Bengali)",
    author: "আমজাদ হোসেন",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400&sig=55",
    bookId: "MAT-7005",
    shelfNo: "MA-3",
    status: "available",
    price: "৳২৭০",
    stock: 7,
    isEBook: false
  },
  {
    title: "Mathematical Optimization and Economic Theory",
    author: "Michael D. Intriligator",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&sig=56",
    bookId: "MAT-7006",
    shelfNo: "MA-3",
    status: "available",
    price: "৳৫৪০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Essential Mathematics for Economic Analysis",
    author: "Knut Sydsæter, Peter Hammond & Andrés Carvajal",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&sig=57",
    bookId: "MAT-7007",
    shelfNo: "MA-1",
    status: "available",
    price: "৳৫৬০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Mathematics for Economics and Business",
    author: "Ian Jacques",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&sig=58",
    bookId: "MAT-7008",
    shelfNo: "MA-4",
    status: "available",
    price: "৳৪৫০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Mathematical Economics: Methods and Models",
    author: "Kamlesh Kumar",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400&sig=59",
    bookId: "MAT-7009",
    shelfNo: "MA-4",
    status: "available",
    price: "৳৩৯০",
    stock: 6,
    isEBook: false
  },
  {
    title: "অর্থনীতিতে গণিতের প্রয়োগ (Application of Mathematics in Economics)",
    author: "প্রফেসর ড. মুহাম্মদ আলী",
    category: "Mathematical Economics (গাণিতিক অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400&sig=60",
    bookId: "MAT-7010",
    shelfNo: "MA-3",
    status: "available",
    price: "৳২৯০",
    stock: 8,
    isEBook: false
  },

  // ==================== 8. PUBLIC FINANCE (10 Books) ====================
  {
    title: "Public Finance",
    author: "Harvey S. Rosen & Ted Gayer",
    category: "Public Finance (সরকারি অর্থব্যবস্থা)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&sig=61",
    bookId: "PUB-8001",
    shelfNo: "P-1",
    status: "available",
    price: "৳৪৯০",
    stock: 6,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-rosen/view"
  },
  {
    title: "Public Finance in Theory and Practice",
    author: "Richard A. Musgrave & Peggy B. Musgrave",
    category: "Public Finance (সরকারি অর্থব্যবস্থা)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&sig=62",
    bookId: "PUB-8002",
    shelfNo: "P-1",
    status: "available",
    price: "৳৫৫০",
    stock: 3,
    isEBook: false
  },
  {
    title: "Economics of the Public Sector",
    author: "Joseph E. Stiglitz & Jay K. Rosengard",
    category: "Public Finance (কোনো ক্যাটাগরি)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&sig=63",
    bookId: "PUB-8003",
    shelfNo: "P-2",
    status: "available",
    price: "৳৫৮০",
    stock: 4,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-stiglitzpublic/view"
  },
  {
    title: "Intermediate Public Economics",
    author: "Jean-Hindriks & Gareth D. Myles",
    category: "Public Finance (সরকারি অর্থব্যবস্থা)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400&sig=64",
    bookId: "PUB-8004",
    shelfNo: "P-2",
    status: "available",
    price: "৳৫১০",
    stock: 5,
    isEBook: false
  },
  {
    title: "সরকারি অর্থব্যবস্থা: থিউরি ও প্যাকটিস (Public Finance Bengali)",
    author: "ড. এম. এইচ. রহমান",
    category: "Public Finance (সরকারি অর্থব্যবস্থা)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400&sig=65",
    bookId: "PUB-8005",
    shelfNo: "P-3",
    status: "available",
    price: "৳৩০০",
    stock: 7,
    isEBook: false
  },
  {
    title: "Modern Public Finance",
    author: "Bernard P. Herber",
    category: "Public Finance (সরকারি অর্থব্যবস্থা)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&sig=66",
    bookId: "PUB-8006",
    shelfNo: "P-3",
    status: "available",
    price: "৳৪৫০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Public Finance: Taxing and Spending",
    author: "David N. Hyman",
    category: "Public Finance (সরকারি অর্থব্যবস্থা)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&sig=67",
    bookId: "PUB-8007",
    shelfNo: "P-1",
    status: "available",
    price: "৳৪২০",
    stock: 6,
    isEBook: false
  },
  {
    title: "Public Economics",
    author: "Gareth D. Myles",
    category: "Public Finance (সরকারি অর্থব্যবস্থা)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&sig=68",
    bookId: "PUB-8008",
    shelfNo: "P-4",
    status: "available",
    price: "৳৫৭০",
    stock: 3,
    isEBook: false
  },
  {
    title: "The Theory of Public Finance",
    author: "Richard Musgrave",
    category: "Public Finance (সরকারি অর্থব্যবস্থা)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400&sig=69",
    bookId: "PUB-8009",
    shelfNo: "P-4",
    status: "available",
    price: "৳৪৮০",
    stock: 5,
    isEBook: false
  },
  {
    title: "সরকারি রাজস্ব নীতি ও বাজেট (Public Revenue Policy and Budget)",
    author: "ড. মশিউর রহমান",
    category: "Public Finance (সরকারি অর্থব্যবস্থা)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400&sig=70",
    bookId: "PUB-8010",
    shelfNo: "P-3",
    status: "available",
    price: "৳২৮০",
    stock: 8,
    isEBook: false
  },

  // ==================== 9. ENVIRONMENTAL ECONOMICS (10 Books) ====================
  {
    title: "Environmental and Natural Resource Economics",
    author: "Tom Tietenberg & Lynne Lewis",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&sig=71",
    bookId: "ENV-9001",
    shelfNo: "EN-1",
    status: "available",
    price: "৳৫২০",
    stock: 5,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-tietenberg/view"
  },
  {
    title: "Environmental Economics: An Introduction",
    author: "Barry C. Field & Martha K. Field",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&sig=72",
    bookId: "ENV-9002",
    shelfNo: "EN-1",
    status: "available",
    price: "৳৪৭০",
    stock: 6,
    isEBook: false
  },
  {
    title: "Natural Resource Economics: An Introduction",
    author: "Barry C. Field",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&sig=73",
    bookId: "ENV-9003",
    shelfNo: "EN-2",
    status: "available",
    price: "৳৪৫০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Environmental Economics",
    author: "Charles D. Kolstad",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400&sig=74",
    bookId: "ENV-9004",
    shelfNo: "EN-2",
    status: "available",
    price: "৳৫৪০",
    stock: 4,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-kolstad/view"
  },
  {
    title: "পরিবেশ অর্থনীতি ও জলবায়ু পরিবর্তন (Environmental Economics Bengali)",
    author: "ড. আশরাফ উদ্দিন দেওয়ান",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400&sig=75",
    bookId: "ENV-9005",
    shelfNo: "EN-3",
    status: "available",
    price: "৳৩৫০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Valuing the Environment: Rain Forest and Biodiversity",
    author: "Edward B. Barbier",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&sig=76",
    bookId: "ENV-9006",
    shelfNo: "EN-3",
    status: "available",
    price: "৳৪৮০",
    stock: 3,
    isEBook: false
  },
  {
    title: "Economics of the Environment",
    author: "Robert N. Stavins",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&sig=77",
    bookId: "ENV-9007",
    shelfNo: "EN-1",
    status: "available",
    price: "৳৫০০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Natural Resources and Environmental Economics",
    author: "Roger Perman, Yue Ma & James McGilvray",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&sig=78",
    bookId: "ENV-9008",
    shelfNo: "EN-4",
    status: "available",
    price: "৳৫৮০",
    stock: 3,
    isEBook: false
  },
  {
    title: "Sustaining Development: Environmental Resource Management",
    author: "Edward Barbier",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400&sig=79",
    bookId: "ENV-9009",
    shelfNo: "EN-4",
    status: "available",
    price: "৳৪৫০",
    stock: 5,
    isEBook: false
  },
  {
    title: "পরিবেশ ও টেকসই উন্নয়নের অর্থনীতি (Economics of Sustainable Dev)",
    author: " ড. খলিলুর রহমান",
    category: "Environmental Economics (পরিবেশ অর্থনীতি)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400&sig=80",
    bookId: "ENV-9010",
    shelfNo: "EN-3",
    status: "available",
    price: "৳৩০০",
    stock: 8,
    isEBook: false
  },

  // ==================== 10. FINANCIAL ECONOMICS & BANKING (10 Books) ====================
  {
    title: "The Economics of Money, Banking, and Financial Markets",
    author: "Frederic S. Mishkin",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400&sig=81",
    bookId: "FIN-10001",
    shelfNo: "F-1",
    status: "available",
    price: "৳৫৯০",
    stock: 6,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-mishkinmoney/view"
  },
  {
    title: "Financial Economics",
    author: "Frank J. Fabozzi, Edwin H. Neave & Guofu Zhou",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400&sig=82",
    bookId: "FIN-10002",
    shelfNo: "F-1",
    status: "available",
    price: "৳৬৪০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Principles of Corporate Finance",
    author: "Richard A. Brealey, Stewart C. Myers & Franklin Allen",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400&sig=83",
    bookId: "FIN-10003",
    shelfNo: "F-2",
    status: "available",
    price: "৳৬৯০",
    stock: 3,
    isEBook: false
  },
  {
    title: "Modern Banking",
    author: "Shelagh Heffernan",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400&sig=84",
    bookId: "FIN-10004",
    shelfNo: "F-2",
    status: "available",
    price: "৳৫৩০",
    stock: 5,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-heffernan/view"
  },
  {
    title: "আর্থিক অর্থনীতি ও ব্যাংকিং তত্ত্ব (Financial Economics & Banking Theory Bengali)",
    author: "ড. খোন্দকার আশরাফ হোসেন",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400&sig=85",
    bookId: "FIN-10005",
    shelfNo: "F-3",
    status: "available",
    price: "৳৩৪০",
    stock: 6,
    isEBook: false
  },
  {
    title: "Corporate Finance: A Focused Approach",
    author: "Michael C. Ehrhardt & Eugene F. Brigham",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&q=80&w=400&sig=86",
    bookId: "FIN-10006",
    shelfNo: "F-3",
    status: "available",
    price: "৳৫২০",
    stock: 5,
    isEBook: false
  },
  {
    title: "Investments",
    author: "Zvi Bodie, Alex Kane & Alan J. Marcus",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400&sig=87",
    bookId: "FIN-10007",
    shelfNo: "F-1",
    status: "available",
    price: "৳৭০০",
    stock: 2,
    isEBook: false
  },
  {
    title: "Commercial Banking: The Management of Risk",
    author: "James R. Kolb & Benton E. Gup",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=400&sig=88",
    bookId: "FIN-10008",
    shelfNo: "F-4",
    status: "available",
    price: "৳৪৫০",
    stock: 4,
    isEBook: false
  },
  {
    title: "Islamic Banking: Theory, Practice and Challenges",
    author: "Muhammad Taqi Usmani",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1491841573178-8af99d009b41?auto=format&fit=crop&q=80&w=400&sig=89",
    bookId: "FIN-10009",
    shelfNo: "F-4",
    status: "available",
    price: "৳৩৫০",
    stock: 7,
    isEBook: true,
    ebookUrl: "https://drive.google.com/file/d/demo-taqiusmani/view"
  },
  {
    title: "আর্থিক বাজার ও ব্যাংক ব্যবস্থার গতিবিধি (Dynamics of Financial Markets & Banking)",
    author: "ড. আতিউর রহমান",
    category: "Financial Economics & Banking (অর্থনীতি ও ব্যাংকিং)",
    cover: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400&sig=90",
    bookId: "FIN-10010",
    shelfNo: "F-3",
    status: "available",
    price: "৳৩২০",
    stock: 8,
    isEBook: false
  }
];
