import React, { useState, useEffect, useMemo, useRef } from 'react';
import { 
  X, ZoomIn, ZoomOut, Maximize2, Minimize2, ChevronLeft, ChevronRight, 
  Search, Highlighter, Plus, Sparkles, AlertCircle, Bookmark, Check, Trash2, 
  BookOpen, Eye, Edit, HelpCircle, Loader2, Play, RefreshCw, Layers, CheckCircle2,
  FileText, Pin, Compass, Info, MessageSquare, ChevronDown
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { db, EbookHighlight, EbookNote, EbookBookmark } from '@/src/lib/supabaseDatabase';
import { cn } from '@/src/lib/utils';

interface PDFViewerProps {
  book: {
    id: string;
    title: string;
    author: string;
    category: string;
    cover: string;
    isEBook?: boolean;
    ebookUrl?: string;
  };
  loggedInUser: {
    id: string;
    name: string;
    email: string;
    role?: string;
  } | null;
  onClose: () => void;
  lang: 'BN' | 'EN';
}

interface SimulatedPage {
  pageNum: number;
  title: string;
  content: string;
  diagramTitle?: string;
  diagramType?: 'graph' | 'table' | 'flow';
  diagramData?: any;
}

// Interactive MCQ interface generated by AI
interface MCQ {
  question: string;
  options: string[];
  answer: number; // 0-3 index
  explanation: string;
  selectedOption?: number | null;
  answeredCorrectly?: boolean | null;
}

export default function PDFViewer({ book, loggedInUser, onClose, lang }: PDFViewerProps) {
  // Navigation & Viewer states
  const [currentPage, setCurrentPage] = useState(1);
  const [zoom, setZoom] = useState(1.0);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [themeMode, setThemeMode] = useState<'light' | 'sepia' | 'dark'>('light');
  
  // Search state
  const [searchQuery, setSearchQuery] = useState('');
  const [searchMatches, setSearchMatches] = useState<{ pageNum: number; count: number }[]>([]);
  const [searchActive, setSearchActive] = useState(false);

  // Database Assets states
  const [highlights, setHighlights] = useState<EbookHighlight[]>([]);
  const [notes, setNotes] = useState<EbookNote[]>([]);
  const [bookmarks, setBookmarks] = useState<EbookBookmark[]>([]);
  
  // Selection Context Menu state
  const [selection, setSelection] = useState<{
    text: string;
    x: number;
    y: number;
    visible: boolean;
  }>({ text: '', x: 0, y: 0, visible: false });

  // Sidebar states
  const [leftSidebarTab, setLeftSidebarTab] = useState<'outline' | 'highlights' | 'notes' | 'bookmarks'>('outline');
  const [isLeftSidebarOpen, setIsLeftSidebarOpen] = useState(true);
  const [isAiSidebarOpen, setIsAiSidebarOpen] = useState(true);

  // AI Study Assistant states
  const [aiLoading, setAiLoading] = useState(false);
  const [aiMessages, setAiMessages] = useState<{ role: 'user' | 'assistant'; text: string; mscqs?: MCQ[] }[]>([
    {
      role: 'assistant',
      text: lang === 'BN' 
        ? `স্বাগতম! আমি আপনার AI স্টাডি অ্যাসিস্ট্যান্ট। আমি এই চ্যাপ্টারের তথ্য বিশ্লেষণ করে সামারি করতে পারি, জটিল বিষয় ব্যাখ্যা করতে পারি এবং আপনার সেলফ-অ্যাসেসমেন্টের জন্য প্র্যাকটিস MCQ তৈরি করতে পারি। আজকের পড়া শুরু করা যাক!` 
        : `Welcome! I'm your AI Study Assistant. I can summarize this page, explain complex terms, highlight formulas, or generate practice quizzes to test your exam preparations. Select any text or use the quick query controls below!`
    }
  ]);
  const [customAiQuery, setCustomAiQuery] = useState('');
  const [quizScore, setQuizScore] = useState<{ correct: number; total: number } | null>(null);

  // Interactive Sticky Note form modal
  const [noteForm, setNoteForm] = useState<{
    isOpen: boolean;
    text: string;
    type: 'sticky' | 'quick' | 'private';
    title: string;
    editId?: string; // set for update
  }>({ isOpen: false, text: '', type: 'sticky', title: '' });

  const containerRef = useRef<HTMLDivElement>(null);
  const contentAreaRef = useRef<HTMLDivElement>(null);

  // Standard high-quality, simulated academic pages for economics/mathematics study guides
  const pages: SimulatedPage[] = useMemo(() => {
    return [
      {
        pageNum: 1,
        title: lang === 'BN' ? "অধ্যায় ১: অর্থশাস্ত্রের মূল সংজ্ঞাসমূহ" : "Chapter 1: Foundational Economic Definitions",
        content: lang === 'BN' 
          ? `অর্থনীতির চর্চা শুরু হয় একটি মৌলিক বাস্তবতার মুখোমুখি হওয়ার মাধ্যমে—সীমাবদ্ধ সম্পদ এবং অসীম চাহিদা। এই দুই বৈপরীত্যের মধ্যে সামঞ্জস্য বিধান করার বৈজ্ঞানিক পদ্ধতিকে অর্থনীতি বা Economics বলা হয়ে থাকে। অধ্যাপক লিওনেল রবিনসের প্রদানকৃত সংজ্ঞা অনুসারে, "অর্থনীতি এমন একটি বিজ্ঞান যা মানুষের অসীম অভাব এবং বিকল্প ব্যবহারযোগ্য সীমিত সম্পদের মধ্যকার সম্পর্ক হিসেবে আচরণ বিশ্লেষণ করে।"

অর্থশাস্ত্রের মূল স্তম্ভটি মূলত অপ্টিমাইজেশন (Optimization) তত্ত্বের ওপর প্রতিষ্ঠিত। সর্বোচ্চ ইউটিলিটি বা উপযোগ বণ্টন কিভাবে অর্জন করা সম্ভব তা গাণিতিকভাবে প্রমাণিত হয়েছে। কন্টিনিউয়াস Cobb-Douglas উৎপাদন অপেক্ষক (Production Function) এর মাধ্যমে যেকোনো একটি ইউনিটের উৎপাদন ক্ষমতা নির্ধারণ করা যায়:

Y = A * K^α * L^(1-α)

এখানে Y দ্বারা মোট উৎপাদন, K দ্বারা মূলধন, L দ্বারা শ্রম এবং A দ্বারা মোট উৎপাদনশীলতার অনুঘটক (TFP) নির্দেশ করা হয়। আক্ষরিক অর্থে, α ও (1-α) যথাক্রমে মূলধন ও শ্রমের স্থিস্থাপকতা প্রদর্শন করে।

অর্থনীতির প্রবৃদ্ধি নিরঙ্কুশ রাখতে প্রডাকশন ফ্রন্টিয়ার বক্ররেখা সর্বদা দক্ষ ভারসাম্যের সীমা নির্দেশ করে থাকে।`
          : `The rigorous study of economics begins with a fundamental reality: scarce resources versus infinite human desires. This tension defines the core optimization problem studied across microeconomic and macroeconomic models. As Lionel Robbins famously defined, "Economics is the science which studies human behavior as a relationship between ends and scarce means which have alternative uses."

At the heart of optimization resides the mathematical concept of maximizing utility or profits under restrictive parameters. For aggregate outputs, the classic Cobb-Douglas Production Function governs long-term growth equations:

Y = A * K^α * L^(1-α)

Where Y represents total output, K is capital input, L is labor input, and A represents Total Factor Productivity (TFP). The parameters α and (1-α) reflect the output elasticities of capital and labor respectively, governing constant returns to scale.

When evaluating production efficiency, the production possibilities frontier (PPF) represents the loci of maximum technological capabilities. Any point lying inside indicates allocative inefficiencies.`,
        diagramType: 'table',
        diagramTitle: lang === 'BN' ? "উৎপাদন স্থিতিস্থাপকতা বিশ্লেষণ সূচক" : "Elasticity and Output Relationships Table",
        diagramData: [
          { index: 1, factor: "Capital (K) Elasticity (α)", value: "0.30", impact: lang === 'BN' ? "মূলধন ঘনত্ব বাড়ায়" : "Capital accumulation yields 30% growth" },
          { index: 2, factor: "Labor (L) Elasticity (1-α)", value: "0.70", impact: lang === 'BN' ? "শ্রম ভিত্তিক উৎপাদন বাড়ায়" : "Labor input dominates production share" },
          { index: 3, factor: "Scale Elasticity Sum", value: "1.00", impact: lang === 'BN' ? "স্থির রিটার্ন নির্দেশ করে" : "Constant Returns to Scale (CRS)" }
        ]
      },
      {
        pageNum: 2,
        title: lang === 'BN' ? "অধ্যায় ২: অপ্টিমাইজেশন থিওরি এবং ল্যাগ্রাঞ্জিয়ান মাল্টিপ্লায়ার" : "Chapter 2: Optimization Theory and Lagrangian Multipliers",
        content: lang === 'BN'
          ? `যখন একজন ভোক্তা বা কোনো উৎপাদনকারী প্রতিষ্ঠান সীমাবদ্ধ সীমার মধ্যে থেকে কোনো গোল বা লক্ষ্য অর্জন করতে চায়, তখন ল্যাগ্রাঞ্জ পদ্ধতি (Lagrange Multiplier Model) অবলম্বন করা হয়। কন্সট্রেইন্ড অপ্টিমাইজেশনের এই জটিল সমস্যাকে সহজ করতে ল্যাগ্রাঞ্জের গুণক λ গুরুত্বপূর্ণ ভূমিকা রাখে।

ধরা যাক, একজন ভোক্তা তার উপযোগিতা অপেক্ষক U(x, y) কে সর্বোচ্চ করতে সচেষ্ট, যেখানে তার বাজেট সীমারেখা হচ্ছে (Income Constraint): px * x + py * y = I.
অপ্টিমাইজেশনের ক্ষেত্রে আমরা ল্যাগ্রাঞ্জ সমীকরণটি এভাবে দাঁড় করাই:

L(x, y, λ) = U(x, y) + λ * (I - px * x - py * y)

প্রথম-মাত্রার শর্তসমূহ (First-Order Conditions - FOC) প্রয়োগের মাধ্যমে আমরা যে চূড়ান্ত অনুপাতটি পাই তা হলো:
MUx / MUy = px / py

যাকে ভোক্তার প্রান্তিক প্রতিস্থাপনের হার বা Marginal Rate of Substitution (MRS) বলা হয়। এটি নির্দেশ করে যে দুটি দ্রব্যের প্রান্তিক উপযোগ ভোগ অনুপাত সর্বদা তাদের আপেক্ষিক মূল্যের সমান হতে হবে। এই ভারসাম্যবিন্দুর অন্যথা হলে ভোক্তা কোনোভাবেই তার উপযোগ সর্বোচ্চ করতে পারবেন না।`
          : `Constrained optimization stands as the analytical backbone for consumer and producer optimization. When individuals aim to maximize their utility with limited financial capacity, the method of Lagrange Multipliers provides an elegant calculus framework.

Consider a consumer seeking to maximize utility U(x, y) subject to the linear budget constraint: px * x + py * y = I.
We formulate the auxiliary Lagrangian objective expression:

L = U(x, y) + λ * (I - px * x - py * y)

Differentiating partially with respect to x, y, and the multiplier λ, the set of First-Order Conditions (FOC) simplifies to the classic equilibrium criterion:
MUx / MUy = px / py

In economic terminology, this equates the Marginal Rate of Substitution (MRS) with the ratio of market prices. Graphically, the consumer achieves maximum satisfaction at the coordinate where the highest possible indifference curve is perfectly tangent to the budget line.`,
        diagramType: 'flow',
        diagramTitle: lang === 'BN' ? "ল্যাগ্রাঞ্জ অপ্টিমাইজেশন ধাপসমূহ" : "Lagrangian Multiplier Pipeline Graph",
        diagramData: lang === 'BN' 
          ? ["১. উপযোগ অপেক্ষক U(x, y) নির্ধারণ", "২. কন্সট্রেইন্ট বাজেট সমীকরণ চিহ্নিতকরণ", "৩. ল্যাগ্রাঞ্জ সমীকরণ L গঠন", "৪. FOC ব্যবকলন ও সমাধান (MRS = Px/Py)"]
          : ["1. State Objective Function U(x, y)", "2. Define linear Constraint (Px X + Py Y = I)", "3. Construct Lagrangian function L", "4. Solve FOC system (Set MRS = Price Ratio)"]
      },
      {
        pageNum: 3,
        title: lang === 'BN' ? "অধ্যায় ৩: সাধারণ ভারসাম্য (General Equilibrium) এবং মার্কেট ক্লিয়ারিং" : "Chapter 3: General Equilibrium Models and Market Clearing",
        content: lang === 'BN'
          ? `সাধারণ ভারসাম্য বলতে এমন এক জটিল পরিস্থিতি বোঝায় যেখানে একটি নির্দিষ্ট অর্থনীতিতে বিরাজমান সবকটি বাজার (পণ্য ও সেবার বাজার এবং মূলধন বা শ্রমের বাজার) একই সাথে ভারসাম্যে উপনীত হয়। অ্যারো-ডেব্রু সাধারণ ভারসাম্য মডেল (Arrow-Debreu Model) গাণিতিকভাবে প্রমাণ করতে সমর্থ হয় যে অবাধ প্রতিযোগিতার অধীনে এমন একটি দক্ষ মূল্য কাঠামো বজায় থাকা সম্ভব যাতে সব বাজার স্বয়ংক্রিয়ভাবে ক্লিয়ারিং হয়ে যায়।

ম্যাক্রোঅর্থনীতির পরিমণ্ডলে, এই সামগ্রিক বাজার অবস্থাকে আমরা IS-LM বক্ররেখার সাহায্যে বুঝতে পারি। 

১. IS (Investment-Saving) সমীকরণ পণ্য বাজারের ভারসাম্য নির্দেশ করে:
Y = C(Y - T) + I(r) + G

২. LM (Liquidity Preference-Money Supply) সমীকরণ অর্থ বাজারের ভারসাম্য নির্দেশ করে:
M/P = L(Y, r)

এখানে Y হলো সামগ্রিক রিয়াল জিডিপি এবং r হলো রিয়াল সুদের হার। যখন সরকার তার পরিকল্পিত ব্যয় G বৃদ্ধি করে, তখন চাহিদার একটি ধনাত্মক ধাক্কা সৃষ্টি হয় যা পণ্য বাজারে IS কার্ভকে ডানপাশে ধাবিত করে। এর ফলে জিডিপি প্রবৃদ্ধি ত্বরান্বিত হয় এবং সুদের হার ঊর্ধ্বমুখী হয়।`
          : `General equilibrium theory encompasses the simultaneous determination of price and quantity across all interconnected markets within an economy. Moving beyond partial equilibrium analysis, Arrow-Debreu mathematical proofs verified that under decentralized, perfectly competitive assumptions, a vector of market-clearing equilibrium prices always exists.

In macroeconomics, this inter-dependent market state is modeled through the classic IS-LM-BP equilibrium:

1. The IS (Investment-Saving) equation governs goods market equilibrium:
Y = C(Y - T) + I(r) + G

2. The LM (Liquidity-Money) equation represents money market cleared states:
M/P = L(Y, r)

Where Y represents real national output, T is tax, G is government expenditure, and r is the prevailing real interest rate. A positive fiscal expansion shifts the IS curve rightward. This increases equilibrium real GDP but simultaneously elevates interest rates, causing some corporate investment crowding out.`,
        diagramType: 'flow',
        diagramTitle: lang === 'BN' ? "IS-LM সামগ্রিক প্রভাব" : "IS-LM Shift Interactions",
        diagramData: lang === 'BN'
          ? ["রিস্কা সরকারি ব্যয় বৃদ্ধি -> পণ্য বাজার চাঙা -> IS কার্ভ ডানপাশে শিফট -> জিডিপি বৃদ্ধি ও সুদ হার বৃদ্ধি -> অর্থ বাজারে অর্থের চাহিদা সৃষ্টি"]
          : ["Deficit Fiscal spending expands -> Goods demand rises -> IS shifts right -> Output GDP grows but drives interest rates (r) upward"]
      },
      {
        pageNum: 4,
        title: lang === 'BN' ? "অধ্যায় ৪: স্টোকাস্টিক রিগ্রেশন এবং ইকোনোমেট্রিক্স ও এর ত্রুটি" : "Chapter 4: Statistical Distributions and Econometric Fit",
        content: lang === 'BN'
          ? `তাত্ত্বিক অর্থনৈতিক মডেলগুলোকে বাস্তব তথ্য বা ডেটার মাধ্যমে যাচাই করার জন্য যে গাণিতিক ও পরিসংখ্যানগত পদ্ধতির প্রয়োগ করা হয় তাকে ইকোনোমেট্রিক্স (Econometrics) বলে। বাস্তব জগতে যেকোনো অর্থনৈতিক চলক সম্পূর্ণ নিখুঁতভাবে হিসেব করা যায় না, কারণ তার সাথে অবশিষ্টাংশ বা স্টোকাস্টিক ডিস্টারবেন্স টার্ম (u) যুক্ত থাকে।

আমাদের সাধারণ লিনিয়ার রিগ্রেশন ইকুয়েশনটি হলো:
Yi = β0 + β1 * X1i + β2 * X2i + ui

এখানে ui হলো হোয়াইট নয়েজ বা ত্রুটি মার্জিন। গাউস-মার্কভ তত্ত্বানুসারে (Gauss-Markov Theorem), যদি অনুমিত ওএলএস ধারণা অক্ষুণ্ণ থাকে, তবে ওএলএস নির্ণয়কারী হবে ব্লু বা BLUE (Best Linear Unbiased Estimator)।

যদি কোনো কারণে অসম সমবিভাজন বা হেটেরোস্কেডাস্টিসিটি (Heteroscedasticity) দেখা দেয়, তবে ওএলএস পরামিতিগুলোর ভ্যারিয়েন্স পক্ষপাতদুষ্ট হয়ে পড়ে। এই সমস্যা সমাধানে আমাদের হোয়াইট-রবাষ্ট স্ট্যান্ডার্ড এরর (Robust Standard Errors) ব্যবহার করে স্টাটিস্টিকাল সিগনিফিকেন্স পুনরুদ্ধার করতে হয়।`
          : `Empirical validation of economic paradigms relies heavily on econometrics. Because real-world variables are subject to countless unpredictable human behaviors and measurement errors, regression models must introduce a stochastic disturbance term (u).

Consider the standard multiple linear regression model:
Yi = β0 + β1 * X1i + β2 * X2i + ui

Where ui represents the random error term enclosing variables not captured explicitly. The Gauss-Markov theorem establishes that under homoscedastic, non-autocorrelated error vectors, the Ordinary Least Squares (OLS) estimator is BLUE (Best Linear Unbiased Estimator).

If errors are heteroscedastic, meaning their variance fluctuates with independent variables, OLS coefficients remain unbiased but lose efficiency. Researchers must utilize Heteroscedasticity-robust covariance estimators (White's Robust Standard Errors) to validate statistical t-tests correctly.`,
        diagramType: 'table',
        diagramTitle: lang === 'BN' ? "OLS গাউস-মার্কভ এজাম্পশন সমূহ" : "Gauss-Markov Blue Criteria Table",
        diagramData: [
          { index: 1, factor: "Expected Error value", value: "E(u_i) = 0", impact: lang === 'BN' ? "রিগ্রেশনে কোনো দীর্ঘস্থায়ী সিস্টেম ব্ল্যাস ছাড়াই সঠিক গড় দেয়" : "Ensures unbiased intercept estimator" },
          { index: 2, factor: "Homoscedasticity", value: "Var(u) = Constant", impact: lang === 'BN' ? "সমান ডাটা বন্টন ও সুষম ত্রুটি মাত্রা বজায় রাখে" : "Guarantees optimal variance for efficiency" },
          { index: 3, factor: "Non-Autocorrelation", value: "Cov(u_i, u_j) = 0", impact: lang === 'BN' ? "পূর্বের বছরগুলোর প্রভাবে বর্তমানের ত্রুটি বাড়ে না" : "Prevents false significance levels in time series" }
        ]
      },
      {
        pageNum: 5,
        title: lang === 'BN' ? "অধ্যায় ৫: পরীক্ষায় সাফল্যের জন্য শেষ মুহূর্তের স্টাডি শিট" : "Chapter 5: Core Revision Notes and High Yield Solved Concepts",
        content: lang === 'BN'
          ? `পড়াশোনা সমাপ্ত করার পর চূড়ান্ত পরীক্ষার সুশৃঙ্খল রিভিশন অপরিহার্য। বিশেষ করে ঢাকা বিশ্ববিদ্যালয় ও মাওলানা ভাসানী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়ের অর্থনীতি পরীক্ষাগুলোতে নিম্নলিখিত টপিকগুলো থেকে প্রশ্ন প্রতি বছর প্রায় ৩০% ভাগ কভার করে থাকে।

পরীক্ষায় সাফল্য লাভের কয়েকটি প্রধান নিয়মাবলী:

১. Cobb-Douglas মডেলের ক্ষেত্রে সর্বদা প্রমাণ করুন যে হোমোজেনাস ডিগ্রি হচ্ছে ১ এবং এর ফলে আইসোডিন বক্ররেখা কেন্দ্রবিন্দু থেকে সোজা হয়ে বহির্গত হয়।

২. IS-LM ভারসাম্য ব্যাখ্যা করার সময় ডায়াগ্রাম অঙ্কন করতে পেনসিল ব্যবহার করুন এবং IS এর ঢাল ঋণাত্মক ও LM এর ঢাল ধনাত্মক হওয়ার কারণ সংক্ষেপে সমীকরণের মাধ্যমে প্রকাশ করুন।

৩. মাল্টিপল রিগ্রেশনে মাল্টিকোলিনিয়ারিটি (Multicollinearity) থাকলে কিভাবে তা VIF (Variance Inflation Factor) টেস্ট করে শনাক্ত করা যায় তা ভালো করে আয়ত্ত করুন। ৩ এর বেশি VIF মান হলে চলকগুলোতে তীব্র ত্রুটি কোরিলেশন নির্দেশ করে থাকে।`
          : `Consistent revision of central frameworks guarantees exceptional performance in major economics semester exams. Historical dataset reviews show that questions concerning substitution elasticities, regression failures, and monetary transmission channels account for up to 35% of overall marks.

High-Yield Examination Tips:

1. Cobb-Douglas Proofs: Be prepared to prove that homogeneous degree equals one. Show that expansion path of constant returns to scale is a straight radial line emitting from origin.

2. Policy Slope Equations: Always derive the mathematical slopes. The goods equilibrium IS slope is negative due to consumption investment interest interactions. The LM money equilibrium is positive because financial demand tracks GDP.

3. Multicollinearity Detection: Understand how high correlation between features inflates variable standard errors. Detect this utilizing the Variance Inflation Factor (VIF). Values greater than 5 warrant correction.`,
        diagramType: 'table',
        diagramTitle: lang === 'BN' ? "পরীক্ষার গুরুত্বপূর্ণ টপিক ও ওয়েটেজ" : "Key Examination Concepts and Marks Weights",
        diagramData: [
          { index: 1, factor: "Lagrangian Optimization Proofs", value: "25% Weight", impact: lang === 'BN' ? "গাণিতিক ডেরাইভেশন সহকারে ভোক্তার ভারসাম্য প্রমাণ" : "Requires partial derivatives and constraint substitution" },
          { index: 2, factor: "IS-LM Policy Shock Diagrams", value: "35% Weight", impact: lang === 'BN' ? "ফিসকাল পলিসি ও ক্রাউডিং আউট সংকটের সচিত্র ব্যাখ্যা।" : "Must illustrate floating vs fixed exchange rates results" },
          { index: 3, factor: "OLS Violations & Multicollinearity", value: "40% Weight", impact: lang === 'BN' ? "হেটেরোকেডাস্টিটি ও ডিটেকশন টেস্ট বিশ্লেষণ।" : "Learn Durbin-Watson diagnostic metrics and robust corrections" }
        ]
      }
    ];
  }, [lang]);

  // Load digital reading assets when viewer mounts
  useEffect(() => {
    let active = true;
    const loadAssets = async () => {
      if (!book || !loggedInUser) return;
      try {
        const [hls, nts, bms] = await Promise.all([
          db.getEbookHighlights(book.id, loggedInUser.id).catch(() => []),
          db.getEbookNotes(book.id, loggedInUser.id).catch(() => []),
          db.getEbookBookmarks(book.id, loggedInUser.id).catch(() => [])
        ]);
        if (active) {
          setHighlights(hls);
          setNotes(nts);
          setBookmarks(bms);
          
          // Optionally restore progress
          const prog = await db.getEbookProgress(book.id, loggedInUser.id).catch(() => null);
          if (active && prog && prog.lastPage) {
            setCurrentPage(prog.lastPage);
          }
        }
      } catch (err) {
        console.error("Error loading reader assets:", err);
      }
    };
    loadAssets();
    return () => { active = false; };
  }, [book, loggedInUser]);

  // Toggle simulated browser full screen mode
  const toggleFullscreen = () => {
    if (!isFullscreen) {
      setIsFullscreen(true);
      // Attempt native fullscreen if supported
      if (containerRef.current?.requestFullscreen) {
        containerRef.current.requestFullscreen().catch(() => {});
      }
    } else {
      setIsFullscreen(false);
      if (document.exitFullscreen) {
        document.exitFullscreen().catch(() => {});
      }
    }
  };

  // Safe handler to exit native fullscreen
  useEffect(() => {
    const handleFullscreenChange = () => {
      setIsFullscreen(document.fullscreenElement === containerRef.current);
    };
    document.addEventListener('fullscreenchange', handleFullscreenChange);
    return () => document.removeEventListener('fullscreenchange', handleFullscreenChange);
  }, []);

  // Update study progress in Database
  const saveProgress = async (pageNum: number) => {
    if (!book || !loggedInUser) return;
    try {
      const completionPercentage = Math.round((pageNum / pages.length) * 100);
      await db.saveEbookProgress({
        bookId: book.id,
        bookTitle: book.title,
        memberId: loggedInUser.id,
        progress: completionPercentage,
        lastPage: pageNum,
        updatedAt: new Date().toLocaleDateString('bn-BD')
      });
    } catch (err) {
      console.warn("Unable to store reading statistics:", err);
    }
  };

  // Change page with progress autosaving
  const handlePageChange = (newPageNum: number) => {
    if (newPageNum < 1 || newPageNum > pages.length) return;
    setCurrentPage(newPageNum);
    saveProgress(newPageNum);
  };

  // Bookmarking Toggle
  const isBookmarked = useMemo(() => {
    return bookmarks.some(bm => bm.pageNumber === currentPage);
  }, [bookmarks, currentPage]);

  const handleToggleBookmark = async () => {
    if (!book || !loggedInUser) return;
    try {
      const match = bookmarks.find(bm => bm.pageNumber === currentPage);
      if (match) {
        await db.deleteEbookBookmark(match.id);
        setBookmarks(prev => prev.filter(bm => bm.id !== match.id));
      } else {
        const result = await db.saveEbookBookmark({
          bookId: book.id,
          memberId: loggedInUser.id,
          pageNumber: currentPage
        });
        setBookmarks(prev => [...prev, result]);
      }
    } catch (err) {
      console.error(err);
    }
  };

  // Search logic
  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim()) {
      setSearchMatches([]);
      setSearchActive(false);
      return;
    }

    const matches: { pageNum: number; count: number }[] = [];
    pages.forEach(p => {
      const lowerText = p.content.toLowerCase();
      const lowerTitle = p.title.toLowerCase();
      const query = searchQuery.toLowerCase();
      
      let count = 0;
      let pos = lowerText.indexOf(query);
      while(pos !== -1) {
        count++;
        pos = lowerText.indexOf(query, pos + 1);
      }
      if (lowerTitle.includes(query)) count++;

      if (count > 0) {
        matches.push({ pageNum: p.pageNum, count });
      }
    });

    setSearchMatches(matches);
    setSearchActive(true);
    
    // Auto navigate to first match if any
    if (matches.length > 0) {
      handlePageChange(matches[0].pageNum);
    }
  };

  // Selection trigger context menu popup
  const handleMouseUp = (e: React.MouseEvent) => {
    const sel = window.getSelection();
    if (!sel || sel.isCollapsed) {
      setSelection(p => ({ ...p, visible: false }));
      return;
    }

    const text = sel.toString().trim();
    if (text.length > 2 && text.length < 500) {
      // Position menu relative to parent page canvas bounding rect
      const rect = selection.text === text ? null : sel.getRangeAt(0).getBoundingClientRect();
      if (rect && contentAreaRef.current) {
        const areaRect = contentAreaRef.current.getBoundingClientRect();
        const popupX = rect.left - areaRect.left + (rect.width / 2);
        const popupY = rect.top - areaRect.top - 50; // slightly above

        setSelection({
          text,
          x: Math.max(10, Math.min(popupX, areaRect.width - 240)),
          y: Math.max(10, popupY),
          visible: true
        });
      }
    }
  };

  // Create highlighted text segment
  const handleCreateHighlight = async (color: 'yellow' | 'blue' | 'green' | 'red' | 'underline') => {
    if (!loggedInUser || !selection.text) return;
    try {
      const textHighlight = selection.text;
      
      // Store 'underline' directly by tagging it or saving special red/blue color
      // Since backend supports 'yellow'|'blue'|'green'|'red', let's treat 'underline' as 'red' highlight or 'blue' highlight, 
      // but save as red/blue and map custom field, OR save directly. Underline fits green/red perfectly.
      // Let's use red as the highlight color for 'underline' if needed, or save with underline option.
      const resolvedColor = color === 'underline' ? 'red' : color;
      
      const res = await db.saveEbookHighlight({
        bookId: book.id,
        memberId: loggedInUser.id,
        pageNumber: currentPage,
        color: resolvedColor,
        text: textHighlight
      });
      
      // Mark custom property isUnderline if underline was chosen
      const localizedWithFlag = {
        ...res,
        isUnderline: color === 'underline'
      };

      setHighlights(prev => [...prev, localizedWithFlag]);
      
      // Clear selection
      window.getSelection()?.removeAllRanges();
      setSelection(p => ({ ...p, visible: false }));
    } catch (err) {
      console.error("Save highlight error:", err);
    }
  };

  // Open note form modal for the selected text
  const handleOpenNoteForSelection = () => {
    if (!selection.text) return;
    setNoteForm({
      isOpen: true,
      text: selection.text,
      title: lang === 'BN' ? `নোট - পৃষ্ঠা ${currentPage}` : `Note - Page ${currentPage}`,
      type: 'sticky'
    });
    setSelection(p => ({ ...p, visible: false }));
  };

  // Text submit Sticky Note
  const handleSaveNote = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!loggedInUser || !noteForm.text.trim()) return;

    try {
      if (noteForm.editId) {
        // Updating existing note
        const res = await db.saveEbookNote({
          id: noteForm.editId,
          bookId: book.id,
          memberId: loggedInUser.id,
          pageNumber: currentPage,
          text: noteForm.text,
          title: noteForm.title || `Note - Page ${currentPage}`,
          type: noteForm.type
        });
        setNotes(prev => prev.map(n => n.id === noteForm.editId ? res : n));
      } else {
        // Saving new note
        const res = await db.saveEbookNote({
          bookId: book.id,
          memberId: loggedInUser.id,
          pageNumber: currentPage,
          text: noteForm.text,
          title: noteForm.title || `Note - Page ${currentPage}`,
          type: noteForm.type
        });
        setNotes(prev => [...prev, res]);
      }
      setNoteForm({ isOpen: false, text: '', type: 'sticky', title: '' });
      window.getSelection()?.removeAllRanges();
    } catch (err) {
      console.error(err);
    }
  };

  // Deleting utilities
  const handleDeleteHighlight = async (id: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    try {
      await db.deleteEbookHighlight(id);
      setHighlights(prev => prev.filter(hl => hl.id !== id));
    } catch (err) {
      console.error(err);
    }
  };

  const handleDeleteNote = async (id: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    try {
      await db.deleteEbookNote(id);
      setNotes(prev => prev.filter(n => n.id !== id));
    } catch (err) {
      console.error(err);
    }
  };

  // AI Study Assistant actions
  const triggerAiAssist = async (action: 'summarize' | 'explain' | 'mcq' | 'custom', textContext?: string) => {
    if (!book) return;
    setAiLoading(true);

    const activePage = pages.find(p => p.pageNum === currentPage);
    const contextContent = activePage?.content || '';

    let promptQuery = '';
    const displayMsg = {
      role: 'user' as const,
      text: ''
    };

    if (action === 'summarize') {
      displayMsg.text = lang === 'BN' 
        ? `পৃষ্ঠা নম্বর ${currentPage} এর সামগ্রিক সারাংশ গিগ বিশ্লেষণ করুন` 
        : `Request Summary for Page ${currentPage}`;
      promptQuery = `Class: Economics Study Material\nBook: "${book.title}" by ${book.author}\nPage Content:\n"${contextContent}"\n\nTask: Provide a detailed, highly technical exam-calibrated summary with clear bullet points.`;
    } else if (action === 'explain') {
      const selectedText = textContext || selection.text || contextContent.substring(0, 200);
      displayMsg.text = lang === 'BN' 
        ? `এই অনুচ্ছেদটি ব্যাখ্যা করুন: "${selectedText.substring(0, 40)}..."` 
        : `Explain this paragraph: "${selectedText.substring(0, 40)}..."`;
      promptQuery = `Class: Economics Study Material\nBook: "${book.title}"\nParagraph:\n"${selectedText}"\n\nTask: Explain the underlying economic concepts, formulas, or logical axioms in simple, highly accessible academic terms for students. Highlight key terms.`;
      // Clear selection coordinates
      setSelection(p => ({ ...p, visible: false }));
    } else if (action === 'mcq') {
      displayMsg.text = lang === 'BN' 
        ? `পৃষ্ঠা ${currentPage} এর ওপর প্র্যাকটিস কুইজ MCQ তৈরি করুন` 
        : `Generate Practice MCQs for Page ${currentPage}`;
      promptQuery = `Class: Economics Study Material\nPage Content:\n"${contextContent}"\n\nTask: Generate exactly 3 Multiple Choice Questions (MCQ) for student revision. Return the output STRICTLY in a JSON array format (do NOT add other texts, markdown frames, or explanation strings outside the JSON block). Each object inside the array must exactly have structural fields:
{
  "question": "question text",
  "options": ["Option A", "Option B", "Option C", "Option D"],
  "answer": 0, // 0-indexed correct option (number)
  "explanation": "brief description why this is correct"
}`;
    } else {
      displayMsg.text = textContext || customAiQuery;
      promptQuery = `Class: Economics Study Material\nBook: "${book.title}"\nPage Content:\n"${contextContent}"\n\nUser Question:\n"${textContext || customAiQuery}"\n\nTask: Provide a helpful, clear academic response.`;
      setCustomAiQuery('');
    }

    setAiMessages(prev => [...prev, displayMsg]);

    try {
      const response = await fetch('/api/gemini/assist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: promptQuery })
      });
      const data = await response.json();
      
      if (data && data.success) {
        if (action === 'mcq') {
          // Attempt parsing MCQ JSON from model
          try {
            // strip markdown artifacts if model wrapped inside ```json...```
            let cleaned = data.result.trim();
            if (cleaned.startsWith('```json')) cleaned = cleaned.replace(/```json/g, '');
            if (cleaned.startsWith('```')) cleaned = cleaned.replace(/```/g, '');
            cleaned = cleaned.trim();

            const mcqs: MCQ[] = JSON.parse(cleaned);
            setAiMessages(prev => [...prev, {
              role: 'assistant',
              text: lang === 'BN' ? "চমৎকার! আপনার জন্য নিচে ৩টি চূড়ান্ত সিলেবাস ভিত্তিক কুইজ রিভিশন তৈরি করেছি:" : "Awesome! I have generated 3 curriculum-focused practice quiz questions for you:",
              mscqs: mcqs.map(q => ({ ...q, selectedOption: null, answeredCorrectly: null }))
            }]);
            setQuizScore({ correct: 0, total: mcqs.length });
          } catch (jsonErr) {
            console.error("MCQ parsing failed. Response raw text was:", data.result);
            setAiMessages(prev => [...prev, {
              role: 'assistant',
              text: data.result // fallback if not outputted exact JSON
            }]);
          }
        } else {
          setAiMessages(prev => [...prev, { role: 'assistant', text: data.result }]);
        }
      } else {
        setAiMessages(prev => [...prev, { role: 'assistant', text: "Error: " + (data.error || "Failed to contact Gemini.") }]);
      }
    } catch (e) {
      setAiMessages(prev => [...prev, { role: 'assistant', text: "Service error. Please verify dev tools." }]);
    } finally {
      setAiLoading(false);
    }
  };

  // MCQ User select answer option handler
  const handleSelectQuizOption = (msgIndex: number, mcqIndex: number, optionIndex: number) => {
    const updatedMessages = [...aiMessages];
    const targetMsg = updatedMessages[msgIndex];
    if (targetMsg && targetMsg.mscqs && targetMsg.mscqs[mcqIndex]) {
      const currentMCQ = targetMsg.mscqs[mcqIndex];
      if (currentMCQ.selectedOption !== null) return; // already answered
      
      currentMCQ.selectedOption = optionIndex;
      currentMCQ.answeredCorrectly = (optionIndex === currentMCQ.answer);

      setAiMessages(updatedMessages);

      // Update aggregate score
      if (quizScore) {
        const isCorrect = currentMCQ.answeredCorrectly;
        setQuizScore(prev => prev ? {
          correct: prev.correct + (isCorrect ? 1 : 0),
          total: prev.total
        } : null);
      }
    }
  };

  // Custom text highlighting renderer to tag intervals elegantly
  const highlightedPageDOM = useMemo(() => {
    const activePage = pages.find(p => p.pageNum === currentPage);
    if (!activePage) return null;

    const pageContent = activePage.content;
    const pageHighlights = highlights.filter(hl => hl.pageNumber === currentPage);

    if (pageHighlights.length === 0) return pageContent;

    // Find non-overlapping intervals of highlights
    const intervals: { start: number; end: number; hl: any }[] = [];
    pageHighlights.forEach(hl => {
      if (!hl.text) return;
      let pos = pageContent.toLowerCase().indexOf(hl.text.toLowerCase());
      while (pos !== -1) {
        // Prevent exact word parts collision
        intervals.push({
          start: pos,
          end: pos + hl.text.length,
          hl
        });
        pos = pageContent.toLowerCase().indexOf(hl.text.toLowerCase(), pos + 1);
      }
    });

    // Sort intervals by start pointer
    intervals.sort((a, b) => a.start - b.start || b.end - a.end);

    // Merge/Filter overlapping highlight ranges
    const filteredIntervals: typeof intervals = [];
    let lastEndOffset = -1;
    intervals.forEach(curr => {
      if (curr.start >= lastEndOffset) {
        filteredIntervals.push(curr);
        lastEndOffset = curr.end;
      }
    });

    const jsxElements: React.ReactNode[] = [];
    let prevIndex = 0;

    filteredIntervals.forEach((interval, idx) => {
      if (interval.start > prevIndex) {
        jsxElements.push(pageContent.substring(prevIndex, interval.start));
      }

      const hlText = pageContent.substring(interval.start, interval.end);
      const isUnderlinType = interval.hl.isUnderline || interval.hl.color === 'red'; // treat red highlight or underline
      
      let styleClasses = "bg-yellow-200/90 text-yellow-950 px-1.5 py-0.5 rounded-md cursor-pointer hover:bg-yellow-300 transition-colors inline-block";
      if (interval.hl.color === 'green') {
        styleClasses = "bg-emerald-200/90 text-emerald-950 px-1.5 py-0.5 rounded-md cursor-pointer hover:bg-emerald-300 transition-colors inline-block";
      } else if (interval.hl.color === 'blue') {
        styleClasses = "bg-sky-200/90 text-sky-950 px-1.5 py-0.5 rounded-md cursor-pointer hover:bg-sky-300 transition-colors inline-block";
      } else if (interval.hl.color === 'red') {
        // red can render as underline styled or subtle pink
        styleClasses = "bg-rose-200/90 text-rose-950 px-1.5 py-0.5 rounded-md cursor-pointer hover:bg-rose-300 transition-colors inline-block";
      }

      if (interval.hl.isUnderline) {
        styleClasses = "underline decoration-wavy decoration-indigo-500 decoration-2 font-semibold cursor-pointer hover:text-indigo-700 transition-all inline-block";
      }

      jsxElements.push(
        <span 
          key={`highlight-${idx}`} 
          className={styleClasses}
          onClick={(e) => {
            e.stopPropagation();
            if (confirm(lang === 'BN' ? 'এই হাইলাইটটি মুছে ফেলতে চান?' : 'Do you want to delete this highlight?')) {
              handleDeleteHighlight(interval.hl.id);
            }
          }}
        >
          {hlText}
        </span>
      );

      prevIndex = interval.end;
    });

    if (prevIndex < pageContent.length) {
      jsxElements.push(pageContent.substring(prevIndex));
    }

    return jsxElements;
  }, [currentPage, pages, highlights, lang]);

  // Page title / Outline navigation helper
  const activeChapterObj = pages.find(p => p.pageNum === currentPage);

  return (
    <div 
      id="pdf-immersive-reader"
      ref={containerRef}
      className={cn(
        "fixed inset-0 z-[140] w-full h-full flex flex-col font-sans transition-all duration-300",
        themeMode === 'light' && "bg-slate-100 text-slate-800",
        themeMode === 'sepia' && "bg-[#f5edd6] text-amber-950",
        themeMode === 'dark' && "bg-slate-950 text-slate-150"
      )}
    >
      {/* Dynamic Reader Toolbar Header with Zoom, Fullscreen, Search & Theme switches */}
      <header className="flex-none flex items-center justify-between px-6 py-4 border-b border-slate-200/40 shadow-sm bg-white/95 text-slate-900 z-10 select-none">
        <div className="flex items-center gap-4">
          <button 
            type="button"
            onClick={onClose}
            className="p-3.5 hover:bg-slate-100 rounded-full transition-colors font-bold flex items-center justify-center cursor-pointer"
            title={lang === 'BN' ? 'পড়া বন্ধ করুন' : 'Exit Reader'}
          >
            <X className="w-5 h-5 text-slate-600" />
          </button>
          
          <div className="flex flex-col">
            <span className="text-[10px] font-black uppercase text-indigo-600 tracking-widest leading-none mb-1">
              {lang === 'BN' ? 'ডিজিটাল ই-বুক রিডার' : 'E-BOOK ACADEMIC READER'}
            </span>
            <h1 className="text-sm font-black text-slate-900 leading-none truncate max-w-[280px]">
              {book.title}
            </h1>
          </div>
        </div>

        {/* Toolbar Controls */}
        <div className="hidden md:flex items-center gap-2">
          {/* Page Indicators */}
          <div className="flex items-center bg-slate-50 border border-slate-200/80 rounded-full p-1.5 mr-2">
            <button 
              type="button"
              disabled={currentPage <= 1}
              onClick={() => handlePageChange(currentPage - 1)}
              className="p-2 disabled:opacity-30 hover:bg-white rounded-full transition-all disabled:pointer-events-none"
            >
              <ChevronLeft className="w-4 h-4 text-slate-700" />
            </button>
            <span className="px-3.5 font-bold text-xs font-mono text-slate-700 min-w-[65px] text-center">
              {lang === 'BN' ? `পৃষ্ঠা ${currentPage} / ${pages.length}` : `Page ${currentPage} / ${pages.length}`}
            </span>
            <button 
              type="button"
              disabled={currentPage >= pages.length}
              onClick={() => handlePageChange(currentPage + 1)}
              className="p-2 disabled:opacity-30 hover:bg-white rounded-full transition-all disabled:pointer-events-none"
            >
              <ChevronRight className="w-4 h-4 text-slate-700" />
            </button>
          </div>

          {/* Zoom Scales */}
          <div className="flex items-center bg-slate-50 border border-slate-200/80 rounded-full p-1 mr-2 font-mono">
            <button 
              type="button"
              disabled={zoom < 0.8}
              onClick={() => setZoom(prev => Math.max(0.7, prev - 0.1))}
              className="p-2 hover:bg-white rounded-full transition"
            >
              <ZoomOut className="w-3.5 h-3.5 text-slate-700" />
            </button>
            <span className="px-2.5 text-[10px] font-extrabold text-slate-700 min-w-[50px] text-center select-none">
              {Math.round(zoom * 100)}%
            </span>
            <button 
              type="button"
              disabled={zoom > 1.8}
              onClick={() => setZoom(prev => Math.min(2.0, prev + 0.1))}
              className="p-2 hover:bg-white rounded-full transition"
            >
              <ZoomIn className="w-3.5 h-3.5 text-slate-700" />
            </button>
          </div>

          {/* Theme selectors */}
          <div className="flex items-center bg-slate-50 border border-slate-200/80 rounded-full p-1 mr-2 text-[10px] font-black uppercase tracking-wider">
            <button 
              type="button"
              onClick={() => setThemeMode('light')}
              className={cn("px-3 py-1.5 rounded-full transition", themeMode === 'light' ? 'bg-white text-indigo-700 shadow-sm font-black' : 'text-slate-500 hover:text-slate-800')}
            >
              {lang === 'BN' ? 'আলো' : 'Light'}
            </button>
            <button 
              type="button"
              onClick={() => setThemeMode('sepia')}
              className={cn("px-3 py-1.5 rounded-full transition", themeMode === 'sepia' ? 'bg-[#f4ebd0] text-amber-900 shadow-sm font-black' : 'text-slate-500 hover:text-slate-800')}
            >
              {lang === 'BN' ? 'সেপিয়া' : 'Sepia'}
            </button>
            <button 
              type="button"
              onClick={() => setThemeMode('dark')}
              className={cn("px-3 py-1.5 rounded-full transition", themeMode === 'dark' ? 'bg-slate-900 text-white shadow-xs font-black' : 'text-slate-500 hover:text-slate-800')}
            >
              {lang === 'BN' ? 'আঁধার' : 'Dark'}
            </button>
          </div>

          {/* Fullscreen Mode */}
          <button 
            type="button"
            onClick={toggleFullscreen}
            className="p-2.5 hover:bg-slate-100 rounded-full transition text-slate-600"
            title={isFullscreen ? (lang === 'BN' ? 'ফুল স্ক্রিন বন্ধ' : 'Exit Fullscreen') : (lang === 'BN' ? 'ফুল স্ক্রিন' : 'Fullscreen')}
          >
            {isFullscreen ? <Minimize2 className="w-4 h-4 text-rose-500 animate-pulse" /> : <Maximize2 className="w-4 h-4" />}
          </button>

          {/* Bookmark Trigger */}
          <button 
            type="button"
            onClick={handleToggleBookmark}
            className={cn("p-2.5 rounded-full transition ml-1 cursor-pointer", isBookmarked ? "bg-amber-100 text-amber-600" : "hover:bg-slate-50 text-slate-400")}
            title={lang === 'BN' ? 'বুকমার্ক করুন' : 'Bookmark this page'}
          >
            <Bookmark className={cn("w-4 h-4", isBookmarked && "fill-current")} />
          </button>
        </div>

        {/* Real-time PDF Inside Search field */}
        <div className="flex items-center gap-1.5">
          <form onSubmit={handleSearch} className="relative flex items-center">
            <input 
              type="text"
              placeholder={lang === 'BN' ? 'ই-বুকে খুঁজুন...' : 'Search inside...'}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="px-5 py-2.5 bg-slate-100 placeholder-slate-400 font-bold text-xs rounded-full focus:outline-none focus:ring-2 focus:ring-indigo-500/30 w-36 md:w-52"
            />
            {searchQuery && (
              <button 
                type="button" 
                onClick={() => { setSearchQuery(''); setSearchMatches([]); setSearchActive(false); }}
                className="absolute right-3 p-1 text-slate-400 hover:text-slate-600"
              >
                <X className="w-3 h-3" />
              </button>
            )}
          </form>
          
          <button 
            type="button"
            onClick={() => setIsLeftSidebarOpen(!isLeftSidebarOpen)}
            className={cn("p-3 rounded-full transition-all border", isLeftSidebarOpen ? "bg-indigo-50 text-indigo-600 border-indigo-100" : "bg-white border-slate-200 text-slate-500 hover:bg-slate-50")}
            title={lang === 'BN' ? 'নেভিগেশন প্যানেল' : 'Outline & Notes Panel'}
          >
            <Layers className="w-4 h-4" />
          </button>

          <button 
            type="button"
            onClick={() => setIsAiSidebarOpen(!isAiSidebarOpen)}
            className={cn("p-3 rounded-full transition-all border shrink-0 bg-transparent animate-bounce-slow", isAiSidebarOpen ? "bg-purple-50 text-purple-600 border-purple-150" : "bg-white border-slate-250 text-purple-600 hover:bg-purple-50")}
            title={lang === 'BN' ? 'এআই স্টাডি অ্যাসিস্ট্যান্ট' : 'AI Assistant Panel'}
          >
            <Sparkles className="w-4 h-4" />
          </button>
        </div>
      </header>

      {/* Main Container Row for Sidebar panels and actual reading book Canvas */}
      <div className="flex-1 flex overflow-hidden w-full relative">
        
        {/* LEFT NAVIGATOR PANEL: Directory Outline, Saved Highlights, Sticky-Notes, and Bookmark listings */}
        <AnimatePresence>
          {isLeftSidebarOpen && (
            <motion.aside 
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: 330, opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              transition={{ duration: 0.25 }}
              className={cn(
                "flex-none h-full border-r flex flex-col z-20 select-none overflow-hidden",
                themeMode === 'dark' ? "bg-slate-900/60 border-slate-800" : "bg-white border-slate-200"
              )}
            >
              {/* Sidebar Tabs */}
              <div className="flex border-b border-slate-200/40 p-2 gap-1 bg-slate-50/50">
                <button
                  type="button"
                  onClick={() => setLeftSidebarTab('outline')}
                  className={cn("flex-1 py-2 text-[10px] font-black uppercase tracking-wider rounded-xl transition", leftSidebarTab === 'outline' ? "bg-white text-indigo-700 shadow-sm border border-slate-100" : "text-slate-400 hover:text-slate-700")}
                >
                  {lang === 'BN' ? 'সূচীপত্র' : 'Outline'}
                </button>
                <button
                  type="button"
                  onClick={() => setLeftSidebarTab('highlights')}
                  className={cn("flex-1 py-2 text-[10px] font-black uppercase tracking-wider rounded-xl transition", leftSidebarTab === 'highlights' ? "bg-white text-indigo-700 shadow-sm border border-slate-100" : "text-slate-400 hover:text-slate-700")}
                >
                  {lang === 'BN' ? 'মার্কস' : 'Highlights'}
                </button>
                <button
                  type="button"
                  onClick={() => setLeftSidebarTab('notes')}
                  className={cn("flex-1 py-2 text-[10px] font-black uppercase tracking-wider rounded-xl transition", leftSidebarTab === 'notes' ? "bg-white text-indigo-700 shadow-sm border border-slate-100" : "text-slate-400 hover:text-slate-700")}
                >
                  {lang === 'BN' ? 'নোটস' : 'Notes'}
                </button>
              </div>

              {/* Sidebar Tab Contents scrollable container */}
              <div className="flex-1 overflow-y-auto p-4 space-y-4">
                
                {/* 1. OUTLINE TAB: Chapter Navigator */}
                {leftSidebarTab === 'outline' && (
                  <div className="space-y-2">
                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest px-2 mb-3">
                      {lang === 'BN' ? 'বইয়ের অধ্যায়সমূহ' : 'E-Book Chapters'}
                    </p>
                    {pages.map((p) => (
                      <button
                        key={p.pageNum}
                        type="button"
                        onClick={() => handlePageChange(p.pageNum)}
                        className={cn(
                          "w-full text-left p-4.5 rounded-2xl border transition-all text-xs flex gap-3 items-start cursor-pointer",
                          p.pageNum === currentPage 
                            ? "bg-indigo-600/10 border-indigo-200 text-indigo-900 font-extrabold shadow-sm"
                            : themeMode === 'dark' 
                              ? "bg-slate-900 border-slate-800 text-slate-300 hover:bg-slate-800"
                              : "bg-slate-50 border-slate-100 text-slate-600 hover:bg-slate-100"
                        )}
                      >
                        <BookOpen className="w-4 h-4 text-indigo-500 shrink-0 mt-0.5" />
                        <div className="flex-1">
                          <p className="line-clamp-2 leading-snug">{p.title}</p>
                          <span className="text-[9px] mt-1 block font-mono font-bold text-slate-400 uppercase">
                            {lang === 'BN' ? `পৃষ্ঠা ${p.pageNum}` : `Page ${p.pageNum}`}
                          </span>
                        </div>
                      </button>
                    ))}
                  </div>
                )}

                {/* 2. HIGHLIGHTS TAB: List of highlighted texts */}
                {leftSidebarTab === 'highlights' && (
                  <div className="space-y-3">
                    <div className="flex items-center justify-between px-1 mb-2">
                      <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                        {lang === 'BN' ? 'সংরক্ষিত হাইলাইটস' : 'Saved Highlights'}
                      </p>
                      <span className="px-2 py-0.5 bg-slate-100 rounded-full text-[9px] font-mono font-black text-slate-600">
                        {highlights.length}
                      </span>
                    </div>

                    {highlights.length === 0 ? (
                      <div className="p-8 text-center text-slate-400 text-xs font-bold leading-normal border-2 border-dashed border-slate-200 rounded-3xl">
                        {lang === 'BN' 
                          ? 'পড়াকালীন ই-বুকের যেকোনো অনুচ্ছেদ মাউস/টাস করে ড্রাগ করে হাইলাইট তৈরি করুন।' 
                          : 'Select text segment in the reader to colorize highlight or add references.'}
                      </div>
                    ) : (
                      highlights.map((hl) => (
                        <div 
                          key={hl.id} 
                          onClick={() => handlePageChange(hl.pageNumber)}
                          className={cn(
                            "p-4 rounded-2xl border text-xs relative group/hl cursor-pointer hover:shadow-md transition duration-200 text-left",
                            hl.color === 'green' ? "bg-emerald-50/50 border-emerald-100" :
                            hl.color === 'blue' ? "bg-sky-50/50 border-sky-100" :
                            "bg-yellow-50/50 border-yellow-100"
                          )}
                        >
                          <div className="flex items-center justify-between gap-2 mb-2">
                            <span className={cn(
                              "px-2.5 py-1 text-[8px] font-black rounded-lg uppercase tracking-wide",
                              hl.color === 'green' ? "bg-emerald-100 text-emerald-800" :
                              hl.color === 'blue' ? "bg-sky-100 text-sky-800" :
                              "bg-yellow-100 text-yellow-800"
                            )}>
                              {lang === 'BN' ? `পৃষ্ঠা ${hl.pageNumber}` : `Page ${hl.pageNumber}`}
                            </span>
                            <button
                              type="button"
                              onClick={(e) => handleDeleteHighlight(hl.id, e)}
                              className="p-1 hover:bg-rose-50 text-slate-300 hover:text-rose-600 rounded transition cursor-pointer"
                              title={lang === 'BN' ? 'মুছে ফেলুন' : 'Remove highlight'}
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                          <p className="line-clamp-3 text-slate-600 italic font-bold">
                            "{hl.text}"
                          </p>
                        </div>
                      ))
                    )}
                  </div>
                )}

                {/* 3. NOTES TAB: List of active sticky comments */}
                {leftSidebarTab === 'notes' && (
                  <div className="space-y-3">
                    <div className="flex items-center justify-between px-1 mb-2">
                      <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                        {lang === 'BN' ? 'ব্যক্তিগত স্টাডি নোটস' : 'Personal Study Notes'}
                      </p>
                      <button 
                        type="button"
                        onClick={() => setNoteForm({ isOpen: true, text: '', title: `Private Note - Page ${currentPage}`, type: 'sticky' })}
                        className="p-1 hover:bg-slate-100 text-indigo-600 rounded-full transition flex items-center justify-center cursor-pointer"
                        title={lang === 'BN' ? 'নতুন নোট' : 'Create note'}
                      >
                        <Plus className="w-4 h-4 font-black" />
                      </button>
                    </div>

                    {notes.length === 0 ? (
                      <div className="p-8 text-center text-slate-400 text-xs font-bold leading-normal border-2 border-dashed border-slate-200 rounded-3xl">
                        {lang === 'BN' 
                          ? 'আপনার কোনো নোট নেই। নতুন নোট যুক্ত করতে টেক্সট সিলেক্ট করুন বা প্লাস বাটনে ক্লিক করুন।' 
                          : 'No notes created for this book. Select words to document private formulas and comments.'}
                      </div>
                    ) : (
                      notes.map((n) => (
                        <div 
                          key={n.id}
                          onClick={() => handlePageChange(n.pageNumber)}
                          className="p-5 bg-amber-50/50 border border-amber-200/60 rounded-2xl relative text-left group/note cursor-pointer hover:shadow hover:bg-amber-50/80 transition"
                        >
                          <div className="flex items-center justify-between gap-2 mb-2">
                            <span className="px-2 py-0.5 bg-amber-250/20 text-[#78350f] text-[9px] font-black uppercase rounded-md tracking-wider">
                              {lang === 'BN' ? `পৃষ্ঠা ${n.pageNumber}` : `Page ${n.pageNumber}`}
                            </span>
                            <div className="flex items-center gap-1 opacity-100 md:opacity-0 group-hover/note:opacity-100 transition-opacity">
                              <button
                                type="button"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  setNoteForm({ isOpen: true, text: n.text, title: n.title, type: n.type, editId: n.id });
                                }}
                                className="p-1 hover:bg-amber-100 text-amber-900 rounded transition"
                                title="Edit note"
                              >
                                <Edit className="w-3.5 h-3.5" />
                              </button>
                              <button
                                type="button"
                                onClick={(e) => handleDeleteNote(n.id, e)}
                                className="p-1 hover:bg-rose-50 text-rose-600 rounded transition"
                                title="Delete note"
                              >
                                <Trash2 className="w-3.5 h-3.5" />
                              </button>
                            </div>
                          </div>
                          <h4 className="font-extrabold text-[#78350f] text-xs mb-1">
                            {n.title}
                          </h4>
                          <p className="text-slate-600 text-xs leading-relaxed font-bold break-all whitespace-pre-wrap">
                            {n.text}
                          </p>
                        </div>
                      ))
                    )}
                  </div>
                )}
              </div>
            </motion.aside>
          )}
        </AnimatePresence>

        {/* STUDY E-BOOK CANVAS (MIDDLE COLUMN): Styled as standard real paper/A4 mockup with zoom adjustments */}
        <main className="flex-1 overflow-y-auto px-4 md:px-12 py-8 flex flex-col items-center">
          
          {/* Active Search matching alerts bar */}
          {searchActive && (
            <div className="w-full max-w-3xl mb-6 p-4 bg-indigo-50 border border-indigo-100 rounded-2xl text-xs flex items-center justify-between text-indigo-900">
              <span className="font-bold">
                🔍 {lang === 'BN' ? 'অনুসন্ধানের ফলাফল:' : 'Inside PDF Search Results:'} {searchMatches.length} {lang === 'BN' ? 'টি পৃষ্ঠায় মিল পাওয়া গেছে' : 'pages found matching keywords'}
              </span>
              <div className="flex gap-2">
                {searchMatches.map((match, i) => (
                  <button 
                    key={i}
                    onClick={() => handlePageChange(match.pageNum)}
                    className={cn(
                      "px-3 py-1 bg-white border font-bold rounded-lg hover:border-indigo-500",
                      currentPage === match.pageNum ? "border-indigo-600 text-indigo-600 bg-indigo-50" : "border-slate-200 text-slate-600"
                    )}
                  >
                    {lang === 'BN' ? `পৃষ্ঠা ${match.pageNum}` : `Page ${match.pageNum}`} ({match.count})
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Actual responsive PDF visual page layout container */}
          <div 
            ref={contentAreaRef}
            onMouseUp={handleMouseUp}
            style={{ transform: `scale(${zoom})`, transformOrigin: 'top center' }}
            className={cn(
              "w-full max-w-2xl min-h-[750px] p-8 md:p-14 rounded-3xl shadow-xl border relative transition-all duration-300 transform font-sans flex flex-col justify-between tracking-normal leading-relaxed text-left",
              themeMode === 'light' && "bg-white text-slate-800 border-slate-200",
              themeMode === 'sepia' && "bg-[#fbf0d9] text-[#4a3b32] border-[#eacf9b]/60 shadow-[#e0d0b0]/30",
              themeMode === 'dark' && "bg-slate-900 text-slate-100 border-slate-800"
            )}
          >
            {/* Page Header outline */}
            <div className="flex items-center justify-between border-b border-slate-100 pb-4 mb-8 select-none">
              <span className="text-[9px] font-black tracking-widest text-slate-400 uppercase">
                {pages.find(p => p.pageNum === currentPage)?.title}
              </span>
              <div className="flex items-center gap-1 text-[9px] font-black text-slate-400 font-mono">
                <span>MBSTU ECONOMIC DIGITAL LABS</span>
              </div>
            </div>

            {/* Custom selection absolute coordinates toolbar (Highlight Options Menu) */}
            <AnimatePresence>
              {selection.visible && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9, y: 10 }}
                  animate={{ opacity: 1, scale: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  style={{ top: selection.y, left: selection.x }}
                  className="absolute z-50 bg-slate-900 text-white p-2 rounded-2xl shadow-2xl flex items-center gap-1.5 select-none"
                  onMouseUp={(e) => e.stopPropagation()} // stop self hide
                >
                  {/* Colors */}
                  <button 
                    type="button"
                    onClick={() => handleCreateHighlight('yellow')}
                    className="p-1.5 hover:bg-slate-800 rounded-lg text-yellow-400 transition"
                    title={lang === 'BN' ? 'হলুদ হাইলাইট' : 'Yellow highlight'}
                  >
                    <span className="w-4 h-4 bg-yellow-400 rounded-full block border-2 border-white" />
                  </button>
                  <button 
                    type="button"
                    onClick={() => handleCreateHighlight('green')}
                    className="p-1.5 hover:bg-slate-800 rounded-lg text-emerald-400 transition"
                    title={lang === 'BN' ? 'সবুজ হাইলাইট' : 'Green highlight'}
                  >
                    <span className="w-4 h-4 bg-emerald-400 rounded-full block border-2 border-white" />
                  </button>
                  <button 
                    type="button"
                    onClick={() => handleCreateHighlight('blue')}
                    className="p-1.5 hover:bg-slate-800 rounded-lg text-sky-400 transition"
                    title={lang === 'BN' ? 'নীল হাইলাইট' : 'Blue highlight'}
                  >
                    <span className="w-4 h-4 bg-sky-400 rounded-full block border-2 border-white" />
                  </button>
                  
                  {/* Underline Toggle */}
                  <button 
                    type="button"
                    onClick={() => handleCreateHighlight('underline')}
                    className="px-2.5 py-1.5 hover:bg-slate-800 rounded-lg text-xs font-bold font-mono text-slate-200 transition border border-slate-700/60 flex items-center gap-1 cursor-pointer"
                    title={lang === 'BN' ? 'আন্ডারলাইন' : 'Underline'}
                  >
                    <span className="underline decoration-wavy decoration-indigo-300">U</span>
                  </button>

                  <div className="w-px h-5 bg-slate-700 mx-0.5" />

                  {/* Ask AI */}
                  <button 
                    type="button"
                    onClick={() => triggerAiAssist('explain')}
                    className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 rounded-lg text-[10px] font-black flex items-center gap-1 transition"
                  >
                    <Sparkles className="w-3.5 h-3.5 text-white" />
                    <span>Explain</span>
                  </button>

                  {/* Sticky private Note */}
                  <button 
                    type="button"
                    onClick={handleOpenNoteForSelection}
                    className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 rounded-lg text-[10px] font-black flex items-center gap-1 transition-all"
                  >
                    <Plus className="w-3 h-3 text-emerald-400" />
                    <span>Note</span>
                  </button>
                </motion.div>
              )}
            </AnimatePresence>

            {/* In-Context visual Sticky Notes pins markers inside page text area container */}
            <div className="absolute right-6 top-24 bottom-12 w-6 flex flex-col gap-2 pointer-events-none z-10 select-none">
              {notes.filter(n => n.pageNumber === currentPage).map((n) => (
                <div 
                  key={n.id}
                  onClick={() => {
                    setNoteForm({ isOpen: true, text: n.text, title: n.title, type: n.type, editId: n.id });
                  }}
                  className="w-7 h-7 bg-amber-500 text-white rounded-full flex items-center justify-center cursor-pointer shadow-md pointer-events-auto hover:bg-amber-600 transition hover:-translate-x-1"
                  title={n.title}
                >
                  <Pin className="w-3.5 h-3.5 font-bold animate-pulse rotate-45" />
                </div>
              ))}
            </div>

            {/* Dynamic Content Page Body */}
            <div className="flex-1 flex flex-col">
              
              {/* Heading title */}
              <h2 className="text-3xl font-black mb-8 leading-snug font-sans tracking-tight">
                {activeChapterObj?.title}
              </h2>

              {/* Main formatted paragraph textual stream rendering highlight tags */}
              <div className="text-sm font-sans font-medium mb-10 leading-[1.8] whitespace-pre-wrap select-text break-words">
                {highlightedPageDOM}
              </div>

              {/* Graphical Diagrams and formulas rendering inside reader canvas natively */}
              {activeChapterObj?.diagramType && (
                <div className="mb-8 p-6 bg-slate-50 border border-slate-200/80 rounded-2xl select-none text-[#1e293b]">
                  <p className="text-[10px] font-black text-indigo-600 uppercase tracking-widest text-center mb-4">
                    📊 {activeChapterObj.diagramTitle}
                  </p>

                  {/* Schema layout type 1: Table list relationships */}
                  {activeChapterObj.diagramType === 'table' && activeChapterObj.diagramData && (
                    <div className="overflow-x-auto">
                      <table className="w-full text-left text-xs border-collapse">
                        <thead>
                          <tr className="border-b border-slate-200">
                            <th className="py-2.5 font-black text-[#64748b]">Variable</th>
                            <th className="py-2.5 font-bold font-mono text-[#64748b]">Value</th>
                            <th className="py-2.5 font-black text-[#64748b]">Analytical Role</th>
                          </tr>
                        </thead>
                        <tbody>
                          {activeChapterObj.diagramData.map((row: any, i: number) => (
                            <tr key={i} className="border-b border-slate-100">
                              <td className="py-2.5 font-bold text-slate-800">{row.factor}</td>
                              <td className="py-2.5 font-bold font-mono text-slate-500">{row.value}</td>
                              <td className="py-2.5 text-slate-500 font-medium">{row.impact}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}

                  {/* Schema layout type 2: Flow stages graphs */}
                  {activeChapterObj.diagramType === 'flow' && activeChapterObj.diagramData && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                      {activeChapterObj.diagramData.map((step: string, i: number) => (
                        <div key={i} className="p-3 bg-white border border-slate-100 rounded-xl shadow-xs text-xs flex gap-2.5 items-center">
                          <span className="w-5 h-5 rounded-full bg-indigo-50 text-indigo-600 font-mono font-black shrink-0 flex items-center justify-center">
                            {i + 1}
                          </span>
                          <span className="font-bold text-slate-700 leading-tight">{step}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Page Footer mockup */}
            <div className="flex items-center justify-between border-t border-slate-150/10 pt-4 mt-8 select-none text-[10px] font-black text-slate-400">
              <span className="tracking-widest uppercase">
                {book.author}
              </span>
              <span className="font-mono">
                {lang === 'BN' ? `পৃষ্ঠা ${currentPage}` : `PAGE ${currentPage}`}
              </span>
            </div>
          </div>
        </main>

        {/* RIGHT COLLAPSIBLE PANEL: AI Study Assistant */}
        <AnimatePresence>
          {isAiSidebarOpen && (
            <motion.aside
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: 380, opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="flex-none h-full border-l bg-slate-900 text-white flex flex-col z-20 select-none overflow-hidden relative"
            >
              <div className="p-5 border-b border-slate-800 flex items-center justify-between bg-slate-950/60">
                <h3 className="text-sm font-black flex items-center gap-2.5 uppercase tracking-wider text-purple-300">
                  <Sparkles className="w-5 h-5 text-indigo-400 animate-pulse" />
                  <span>{lang === 'BN' ? 'এআই স্টাডি অ্যাসিস্ট্যান্ট' : 'AI Study Assistant'}</span>
                </h3>
                <button
                  type="button"
                  onClick={() => setIsAiSidebarOpen(false)}
                  className="p-1 hover:bg-slate-800 rounded transition cursor-pointer"
                >
                  <X className="w-4 h-4 text-slate-400" />
                </button>
              </div>

              {/* Study Assistant Quick Action Menu Bar */}
              <div className="p-3 border-b border-slate-800 bg-slate-900/80 flex flex-wrap gap-1.5 justify-center">
                <button
                  type="button"
                  onClick={() => triggerAiAssist('summarize')}
                  className="px-3.5 py-2 bg-slate-850 hover:bg-indigo-600 border border-slate-800 text-xs font-black rounded-full flex items-center gap-1.5 transition duration-150 cursor-pointer"
                  title="Generate Page Summary"
                >
                  <FileText className="w-3.5 h-3.5 text-sky-400" />
                  <span>{lang === 'BN' ? 'সামারি' : 'Page Summary'}</span>
                </button>
                <button
                  type="button"
                  onClick={() => triggerAiAssist('mcq')}
                  className="px-3.5 py-2 bg-slate-850 hover:bg-indigo-600 border border-slate-800 text-xs font-black rounded-full flex items-center gap-1.5 transition duration-150 cursor-pointer"
                  title="Generate Practice MCQs"
                >
                  <Compass className="w-3.5 h-3.5 text-emerald-400" />
                  <span>{lang === 'BN' ? 'গিগ কুইজ' : 'Practice MCQs'}</span>
                </button>
                <button
                  type="button"
                  onClick={() => triggerAiAssist('explain')}
                  className="px-3 py-2 bg-slate-850 hover:bg-indigo-600 border border-slate-800 text-xs font-black rounded-full flex items-center gap-1.5 transition duration-150 cursor-pointer"
                  title="Explain Key Highlights"
                >
                  <Info className="w-3.5 h-3.5 text-amber-400" />
                  <span>{lang === 'BN' ? 'ব্যাখ্যা করুন' : 'Explain Page'}</span>
                </button>
              </div>

              {/* AI Message Stream Chat Canvas scrollable */}
              <div className="flex-1 overflow-y-auto p-5 space-y-5 flex flex-col">
                {aiMessages.map((msg, i) => (
                  <div key={i} className={cn("space-y-3 p-4.5 rounded-2xl w-full text-left bg-slate-950/40 relative font-sans leading-relaxed text-xs", msg.role === 'user' ? "border-l-4 border-indigo-500 self-end bg-indigo-950/20" : "border-l-4 border-purple-500 bg-slate-950/60")}>
                    
                    {/* Speaker indicator tag */}
                    <span className={cn("text-[9px] font-black uppercase tracking-wider block mb-2", msg.role === 'user' ? 'text-indigo-400' : 'text-purple-400')}>
                      {msg.role === 'user' ? (lang === 'BN' ? 'আপনি' : 'You') : (lang === 'BN' ? 'এআই টিউটর' : 'AI STUDY COACH')}
                    </span>

                    {/* text content display */}
                    <div className="font-medium text-slate-200 leading-relaxed whitespace-pre-wrap">
                      {msg.text}
                    </div>

                    {/* Render Interactive MCQs if generated by model AI */}
                    {msg.mscqs && msg.mscqs.length > 0 && (
                      <div className="mt-5 space-y-6 pt-4 border-t border-slate-850">
                        {msg.mscqs.map((q, qIdx) => {
                          const isIncorrectTried = q.selectedOption !== null && q.selectedOption !== q.answer;
                          
                          return (
                            <div key={qIdx} className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-3">
                              <p className="font-extrabold text-slate-100 text-xs">
                                {qIdx + 1}. {q.question}
                              </p>
                              
                              <div className="space-y-2">
                                {q.options.map((opt, oIdx) => {
                                  const isSelected = q.selectedOption === oIdx;
                                  const isCorrectAnswer = q.answer === oIdx;
                                  const hasBeenAnswered = q.selectedOption !== null;

                                  let optClass = "w-full text-left p-3 rounded-lg border text-xs font-semibold cursor-pointer transition-all flex items-center justify-between ";
                                  if (!hasBeenAnswered) {
                                    optClass += "bg-slate-850 hover:bg-slate-800 border-slate-700 text-slate-300 hover:text-white";
                                  } else {
                                    if (isCorrectAnswer) {
                                      optClass += "bg-emerald-950/60 border-emerald-500 text-emerald-250";
                                    } else if (isSelected) {
                                      optClass += "bg-rose-950/60 border-rose-500 text-rose-250";
                                    } else {
                                      optClass += "bg-slate-850 opacity-40 border-slate-800 text-slate-500 cursor-not-allowed";
                                    }
                                  }

                                  return (
                                    <button
                                      key={oIdx}
                                      type="button"
                                      onClick={() => handleSelectQuizOption(i, qIdx, oIdx)}
                                      disabled={hasBeenAnswered}
                                      className={optClass}
                                    >
                                      <span>{opt}</span>
                                      {hasBeenAnswered && isCorrectAnswer && (
                                        <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 ml-1.5" />
                                      )}
                                      {hasBeenAnswered && isSelected && !isCorrectAnswer && (
                                        <AlertCircle className="w-4 h-4 text-rose-400 shrink-0 ml-1.5" />
                                      )}
                                    </button>
                                  );
                                })}
                              </div>

                              {/* MCQ Explanations box */}
                              {q.selectedOption !== null && (
                                <div className="p-3 bg-slate-950 rounded-lg text-[10px] leading-relaxed text-slate-400 border-l border-slate-800 font-bold">
                                  <span className="text-slate-300 font-extrabold block mb-0.5">
                                    💡 {lang === 'BN' ? 'উত্তর বিশ্লেষণ:' : 'Analytical Explanation:'}
                                  </span>
                                  {q.explanation}
                                </div>
                              )}
                            </div>
                          );
                        })}

                        {/* Total score summary box */}
                        {quizScore && (
                          <div className="p-4 bg-emerald-950/25 border border-emerald-500/25 rounded-2xl flex items-center justify-between text-xs font-bold text-emerald-300 select-none">
                            <span>🏆 {lang === 'BN' ? 'প্রাপ্ত স্কোর:' : 'Your Assessment Score:'}</span>
                            <span className="font-mono font-black text-sm bg-emerald-950 px-3.5 py-1 rounded-full">
                              {msg.mscqs.filter(q => q.answeredCorrectly).length} / {msg.mscqs.length}
                            </span>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                ))}

                {/* AI Is Working loaders */}
                {aiLoading && (
                  <div className="p-5 bg-slate-950/40 rounded-2xl border-l-[3px] border-amber-500 flex items-center gap-3 text-xs text-amber-400 font-bold self-start animate-pulse w-full text-left">
                    <Loader2 className="w-5 h-5 animate-spin text-amber-500" />
                    <span>{lang === 'BN' ? 'এআই চিন্তা করছে...' : 'AI Tutor formulating concepts...'}</span>
                  </div>
                )}
              </div>

              {/* Chat Input box footer */}
              <form 
                onSubmit={(e) => { e.preventDefault(); triggerAiAssist('custom'); }}
                className="p-4 bg-slate-950 border-t border-slate-800 flex items-center gap-2 select-none"
              >
                <input 
                  type="text"
                  placeholder={lang === 'BN' ? 'অর্থনৈতিক সমস্যা সমাধান করুন...' : 'Ask AI anything about the PDF...'}
                  value={customAiQuery}
                  onChange={(e) => setCustomAiQuery(e.target.value)}
                  className="flex-1 px-4.5 py-3.5 bg-slate-850 border border-slate-850 hover:border-slate-800 focus:border-indigo-500 rounded-xl text-xs font-bold font-mono placeholder-slate-500 focus:outline-none"
                />
                <button 
                  type="submit"
                  disabled={aiLoading || !customAiQuery.trim()}
                  className="p-3.5 bg-indigo-600 hover:bg-slate-950 text-white disabled:opacity-30 rounded-xl transition cursor-pointer shrink-0"
                >
                  <Sparkles className="w-4 h-4 text-white font-black" />
                </button>
              </form>
            </motion.aside>
          )}
        </AnimatePresence>
      </div>

      {/* MODAL NOTE WRITING / EDITING POPUP */}
      <AnimatePresence>
        {noteForm.isOpen && (
          <div className="fixed inset-0 z-[160] flex items-center justify-center p-4">
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-slate-950/80 backdrop-blur-xs select-none"
              onClick={() => setNoteForm({ isOpen: false, text: '', type: 'sticky', title: '' })}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative bg-white text-slate-800 w-full max-w-lg rounded-[36px] shadow-2xl p-8 border border-white/20 select-none overflow-hidden"
            >
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-xl font-black text-slate-900 flex items-center gap-2.5">
                  <span className="p-2.5 bg-indigo-50 text-indigo-600 rounded-xl">
                    <Pin className="w-4 h-4" />
                  </span>
                  <span>{noteForm.editId ? (lang === 'BN' ? 'নোট সম্পাদনা' : 'Edit Sticky Note') : (lang === 'BN' ? 'নতুন স্টাডি নোট' : 'New Study Note')}</span>
                </h3>
                <button 
                  onClick={() => setNoteForm({ isOpen: false, text: '', type: 'sticky', title: '' })}
                  className="p-2.5 bg-slate-50 hover:bg-slate-100 rounded-full text-slate-400 transition cursor-pointer"
                >
                  <X className="w-4 h-4 text-slate-500" />
                </button>
              </div>

              <form onSubmit={handleSaveNote} className="space-y-4 text-left">
                <div>
                  <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5 ml-1">
                    {lang === 'BN' ? 'নোটের শিরোনাম' : 'Note Title'}
                  </label>
                  <input 
                    type="text" 
                    required
                    className="w-full px-5 py-3 bg-slate-50 border border-slate-100 rounded-xl font-bold text-xs focus:outline-none focus:ring-4 focus:ring-indigo-600/10 placeholder-slate-400"
                    placeholder="e.g. Cobb-Douglas Model Formula"
                    value={noteForm.title}
                    onChange={(e) => setNoteForm({ ...noteForm, title: e.target.value })}
                  />
                </div>
                
                <div>
                  <label className="block text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1.5 ml-1">
                    {lang === 'BN' ? 'নোটের বিস্তারিত বিষয়বস্তু' : 'My Personal Lesson Insight'}
                  </label>
                  <textarea 
                    required
                    rows={4}
                    className="w-full px-5 py-4 bg-slate-50 border border-slate-100 rounded-2xl font-bold text-xs focus:outline-none focus:ring-4 focus:ring-indigo-600/10 placeholder-slate-400 resize-none leading-relaxed"
                    placeholder={lang === 'BN' ? 'এখানে আপনার ব্যাখ্যা বা পড়াশোনার সূত্র সংরক্ষণ করুন...' : 'Write your custom lesson formulas, references or revision comments...'}
                    value={noteForm.text}
                    onChange={(e) => setNoteForm({ ...noteForm, text: e.target.value })}
                  />
                </div>

                <div className="flex items-center gap-4 p-4.5 bg-slate-50 rounded-2xl border border-slate-100/50 select-none">
                  <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest leading-none">
                    {lang === 'BN' ? 'গোপনীয়তা ধরণ:' : 'Security Classification:'}
                  </span>
                  <div className="flex bg-slate-200 p-1 rounded-xl text-[9px] font-black tracking-wider uppercase">
                    {(['sticky', 'quick', 'private'] as const).map((typeVal) => (
                      <button
                        key={typeVal}
                        type="button"
                        onClick={() => setNoteForm({ ...noteForm, type: typeVal })}
                        className={cn("px-3 py-1.5 rounded-lg transition-all", noteForm.type === typeVal ? "bg-indigo-600 text-white font-black shadow-sm" : "text-slate-500 hover:text-slate-800")}
                      >
                        {typeVal}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="pt-4 border-t border-slate-100 flex items-center justify-end gap-2.5">
                  <button 
                    type="button" 
                    onClick={() => setNoteForm({ isOpen: false, text: '', type: 'sticky', title: '' })} 
                    className="px-5 py-3 hover:bg-slate-50 rounded-xl text-xs font-bold text-slate-500 transition cursor-pointer"
                  >
                    {lang === 'BN' ? 'বাতিল' : 'Cancel'}
                  </button>
                  <button 
                    type="submit" 
                    className="px-7 py-3 bg-indigo-600 text-white rounded-xl text-xs font-black shadow-lg shadow-indigo-100 flex items-center gap-2 cursor-pointer"
                  >
                    <Check className="w-4 h-4 text-white" />
                    <span>{noteForm.editId ? (lang === 'BN' ? 'সংরক্ষণ করুন' : 'Update Note') : (lang === 'BN' ? 'যুক্ত করুন' : 'Save Note')}</span>
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
